import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import assert from 'node:assert/strict';
import ts from 'typescript';
import XLSX from 'xlsx';
const tmp=await fs.mkdtemp(path.join(os.tmpdir(),'mondepars-totals-'));
for(const name of ['presence-stock','model','imports','totals']){const src=await fs.readFile(new URL(`../lib/${name}.ts`,import.meta.url),'utf8');await fs.writeFile(path.join(tmp,name+'.mjs'),ts.transpileModule(src,{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText.replace(/from '(\.\/[^']+)'/g,"from '$1.mjs'"))}
const {defaultStores}=await import(path.join(tmp,'model.mjs')),i=await import(path.join(tmp,'imports.mjs')),t=await import(path.join(tmp,'totals.mjs'));const start='2026-09-01',end='2026-09-30';
let all=[],count=0;const input=process.argv[2];if(!input)throw Error('Passe o diretório com os quatro Excel de referência.');const files=(await fs.readdir(input)).filter(f=>/^TOTAL.*\.xlsx$/i.test(f));assert.equal(files.length,4);
for(const file of files){const wb=XLSX.readFile(path.join(input,file)),raw=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]]),id=/\bJK\b/i.test(file)?'02':/\bRJ\b/i.test(file)?'05':/\bBC\b/i.test(file)?'BC':'03';const result=i.normalizeRows(raw,i.guessMapping(Object.keys(raw[0]),'totals'),'totals',defaultStores,{store:id,start,end});assert.deepEqual(result.errors,[]);i.validateNormalized(result.rows,'totals',defaultStores);assert.equal(result.rows.length,raw.length);assert.equal(result.rows.reduce((a,r)=>a+r.qty,0),raw.reduce((a,r)=>a+r.QT,0));assert.equal(result.rows.reduce((a,r)=>a+Math.round(r.amount*100),0),raw.reduce((a,r)=>a+Math.round(r.VALOR*100),0));assert.deepEqual(result.rows.map(r=>r.reference),raw.map(r=>r.REFERENCIA));all.push(...result.rows);count+=5;console.log(`${file}: ${result.rows.length} linhas válidas, quantidades e centavos conciliados.`)}
assert.equal(all.length,544);const sum=t.summarizeTotals(all,defaultStores,start,end);assert.equal(sum.channels.filter(c=>c.hasData).length,4);assert.equal(sum.missing.length,0);assert.equal(sum.negativeRows.length,10);assert.deepEqual(sum.adjustments.map(r=>({store:r.store,qty:r.qty,amount:r.amount})),[{store:'03',qty:0,amount:-86}]);assert.equal(t.summarizeTotals(all,defaultStores,start,'2026-09-29').rows.length,0,'monthly data not allocated to partial period');assert.equal(t.summarizeTotals(all,defaultStores,start,end,'BC').rows.length,94);assert.equal(t.totalsReport(all,defaultStores,start,end).ticket,null);assert.equal(t.totalsReport(all,defaultStores,start,end).actions.length,0);assert.throws(()=>i.validateNormalized([...all.slice(0,1),all[0]],'totals',defaultStores));assert.throws(()=>i.validateNormalized(all,'totals',defaultStores),'single unit per batch');assert.throws(()=>i.validateNormalized([{...all[0],start:'2026-09-31'}],'totals',defaultStores));count+=12;
await fs.rm(tmp,{recursive:true,force:true});console.log(`${count} verificações de importação e consolidação passaram. Nenhum pedido, estoque ou dia de venda artificial foi criado.`);
