import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import ts from 'typescript';
const tmp=await fs.mkdtemp(path.join(os.tmpdir(),'mondepars-v2-'));
for(const name of ['presence-stock','model','totals','operations','demo-operations','imports','report','ai-core']){const source=await fs.readFile(new URL(`../lib/${name}.ts`,import.meta.url),'utf8');const out=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText.replace(/from '(\.\/[^']+)'/g,"from '$1.mjs'");await fs.writeFile(path.join(tmp,name+'.mjs'),out)}
const m=await import(path.join(tmp,'model.mjs')),o=await import(path.join(tmp,'operations.mjs')),i=await import(path.join(tmp,'imports.mjs')),ai=await import(path.join(tmp,'ai-core.mjs')),demo=await import(path.join(tmp,'demo-operations.mjs')),report=await import(path.join(tmp,'report.mjs'));
let assertions=0;function check(value,message){assert.ok(value,message);assertions++}function equal(a,b,message){assert.deepEqual(a,b,message);assertions++}
const end='2026-09-26',stores=[{id:'A',name:'Loja A',type:'store',status:'open',opened:'2026-01-01',target:0},{id:'B',name:'Loja B',type:'store',status:'open',opened:'2026-01-01',target:0},{id:'E',name:'E-commerce',type:'online',status:'open',opened:'2026-01-01',target:0},{id:'N',name:'Nova',type:'store',status:'planned',opened:'2026-10-01',target:0}];
function fixture(){const data={sales:[],stock:[],products:[{sku:'SKU',model:'Camisa',category:'Camisa',color:'Preta',size:'P',cost:20,collection:'2026'}],goals:[],purchases:[],controls:[]};for(const s of stores){for(let n=0;n<28;n++){const date=m.shift(end,-n);data.sales.push({id:`${s.id}:${date}`,order:date,store:s.id,date,sku:'SKU',qty:1,amount:100,discount:0,status:'sale'});data.stock.push({id:`${date}:${s.id}:SKU`,date,store:s.id,sku:'SKU',physical:s.id==='B'?100:s.id==='N'?999:2,reserved:0,incoming:0});data.controls.push({id:`${s.id}:${date}`,store:s.id,date,revenue:100,units:1})}}return data}
const config={...o.defaultOps,leadDays:7,targetDays:14,safetyDays:2,routes:[{from:'B',to:'A',days:1,fixedCost:10,unitCost:1},{from:'B',to:'E',days:2,fixedCost:10,unitCost:1}]};let d=fixture(),plan=o.anticipate(d,stores,end,config);
equal(plan.rows.length,3,'planned stores excluded');equal(plan.quality.every(q=>q.status==='ready'),true,'full reconciliation');equal(plan.rows.find(r=>r.store==='A').daily,1,'demand per confirmed available day');equal(plan.decisions.filter(r=>r.type==='transfer').reduce((a,r)=>a+r.qty,0),24,'separate unit transfer allocations');check(plan.decisions.filter(r=>r.type==='transfer').every(r=>r.from==='B'),'explicit routes only');check(!o.anticipate(d,stores,end,{...config,routes:[]}).decisions.some(r=>r.type==='transfer'),'online stock not automatically pooled');
const approved={dataset:'real',status:'approved',payload:JSON.stringify({...plan.decisions[0],qty:65})};const reserved=o.anticipate(d,stores,end,config,[approved]);check(!reserved.decisions.some(r=>r.to===plan.decisions[0].to),'approved destination not proposed again');check(reserved.decisions.filter(r=>r.from==='B').reduce((a,r)=>a+r.qty,0)<=5,'approved outgoing reservation protects origin');
const done={...approved,status:'done'};check(!o.anticipate(d,stores,end,config,[done]).decisions.some(r=>r.to===plan.decisions[0].to),'completed same snapshot not repeated');check(o.anticipate(d,stores,end,config,[done]).decisions.filter(r=>r.from==='B').reduce((a,r)=>a+r.qty,0)<=5,'completed outgoing remains reserved until a newer snapshot');
d=fixture();d.stock.forEach(s=>s.incoming=999);const base=o.anticipate(d,stores,end,{...config,routes:[]}).rows.find(r=>r.store==='A');equal(base.qty,12,'undated incoming excluded');d.purchases.push({id:'PC1',date:'2026-09-20',expected:m.shift(end,4),store:'A',sku:'SKU',supplier:'Test',qty:10,received:3,unitCost:20,status:'open'});let incoming=o.anticipate(d,stores,end,{...config,routes:[]});let a=incoming.rows.find(r=>r.store==='A');equal(a.datedIncoming,7,'only unreceived remainder counted');equal(a.projection[0].balance,2,'one dated arrival, counted once');equal(a.qty,5,'incoming reduces buy requirement once');check(incoming.decisions.some(x=>x.id.endsWith(':expedite')),'expedite existing order arriving after shortage');
d.purchases[0].expected=m.shift(end,-1);a=o.anticipate(d,stores,end,config).rows.find(r=>r.store==='A');equal(a.datedIncoming,0,'late order excluded');equal(a.qty,12,'late order not assumed received');
d=fixture();d.controls.find(c=>c.store==='A').revenue=80;plan=o.anticipate(d,stores,end,config);check(!plan.decisions.some(x=>x.to==='A'),'mismatched store recommendations blocked');equal(plan.quality.find(q=>q.store==='A').checks[0].difference,20,'reconciliation sign');
d=fixture();d.stock=d.stock.filter(s=>s.store!=='A'||s.date<=m.shift(end,-2));check(!o.anticipate(d,stores,end,config).decisions.some(x=>x.to==='A'),'stale snapshot blocks recommendations');
d=fixture();d.stock.filter(s=>s.store==='A').forEach((s,n)=>{if(n>=7)s.physical=0});d.sales=d.sales.filter(s=>s.store!=='A'||s.date>=m.shift(end,-6));d.controls.filter(c=>c.store==='A'&&c.date<m.shift(end,-6)).forEach(c=>{c.revenue=0;c.units=0});a=o.anticipate(d,stores,end,config).rows.find(r=>r.store==='A');equal(a.daily,1,'availability adjustment excludes verified zero-stock days');equal(a.availableDays,7,'seven available observations');
d=fixture();const rules={...config,routes:[],rules:[{sku:'SKU',leadDays:7,minimum:20,multiple:6}]};equal(o.anticipate(d,stores,end,rules).rows.find(r=>r.store==='A').qty,24,'minimum order and pack multiple');
const raw=[{id:'PC',loja:'A',sku:'SKU',fornecedor:'Teste',data:'26/09/2026',entrega_prevista:'10/10/2026',quantidade:20,recebido:3,custo_unitario:'20,50',status:'aberto'}];const result=i.normalizeRows(raw,i.guessMapping(Object.keys(raw[0]),'purchases'),'purchases',stores);equal(result.errors,[],'purchase import valid');equal(result.rows[0].unitCost,20.5,'decimal BR');i.validateNormalized(result.rows,'purchases',stores);check(true,'server purchase validation');const invalid=i.normalizeRows([{...raw[0],recebido:21}],i.guessMapping(Object.keys(raw[0]),'purchases'),'purchases',stores);equal(invalid.errors.length,1,'received above ordered rejected');
const demoData=demo.demoOperationalData();const snapshot=report.reportSnapshot(demoData,m.defaultStores,end,'Mensal','demo');equal(snapshot.revenue,m.aggregate(demoData,m.defaultStores,'2026-09-01',end,'all').revenue,'V2 report matches deterministic dashboard');check(snapshot.insights.some(s=>s.startsWith('Qualidade:')),'report includes reliability');
const master=btoa(String.fromCharCode(...crypto.getRandomValues(new Uint8Array(32)))),secret='secret-test-key-123456',cipher=await ai.sealKey(secret,master,'p:openai');check(!cipher.includes(secret),'no plaintext in stored cipher');equal(await ai.openKey(cipher,master,'p:openai'),secret,'credential decrypts');await assert.rejects(()=>ai.openKey(cipher,master,'other:openai'));assertions++;
const responses={openai:{output:[{content:[{type:'output_text',text:'Análise'}]}],usage:{input_tokens:2,output_tokens:3}},anthropic:{content:[{type:'text',text:'Análise'}],usage:{input_tokens:2,output_tokens:3}},google:{candidates:[{content:{parts:[{text:'Análise'}]}}],usageMetadata:{promptTokenCount:2,candidatesTokenCount:3}},groq:{choices:[{message:{content:'Análise'}}],usage:{prompt_tokens:2,completion_tokens:3}},deepseek:{choices:[{message:{content:'Análise'}}],usage:{prompt_tokens:2,completion_tokens:3}},openrouter:{choices:[{message:{content:'Análise'}}],usage:{prompt_tokens:2,completion_tokens:3}}};
for(const provider of Object.keys(ai.providers)){let call;const result=await ai.invokeProvider({id:'p',name:'Test',provider,model:'test-model',enabled:true},secret,'{"revenue":100}',false,async(url,options)=>{call={url,options};return Response.json(responses[provider])});equal(result.text,'Análise',provider+' adapter output');equal(result.input,2,provider+' usage');check(!call.url.includes(secret),'no credential in URL');check(!call.options.body.includes(secret),'no credential in prompt');equal(call.options.redirect,'error','no cross-host credential redirects');if(provider==='openai')equal(JSON.parse(call.options.body).store,false,'OpenAI storage disabled')}
const profile={id:'p',name:'Test',provider:'openai',model:'test',enabled:true};await assert.rejects(()=>ai.invokeProvider(profile,secret,'test',false,async()=>new Response('{"key":"'+secret+'"}',{status:401})),e=>!e.retryable&&!e.message.includes(secret));assertions++;
await assert.rejects(()=>ai.invokeProvider(profile,secret,'test',false,async()=>new Response('',{status:503})),e=>e.retryable);assertions++;
const redacted=await ai.invokeProvider(profile,secret,'test',false,async()=>Response.json({output:[{content:[{type:'output_text',text:secret}]}]}));check(!redacted.text.includes(secret),'redact echoed credential');assert.throws(()=>ai.validateProfile({...profile,provider:'__proto__'}));assertions++;
await fs.rm(tmp,{recursive:true,force:true});console.log(`${assertions} verificações passaram: conciliação, estoque, compras, reservas, relatórios, importação, criptografia e 6 adaptadores de IA (respostas simuladas).`);
