import {summarizeTotals,validDate} from '@/lib/totals';
import {database,json,readRecords} from '@/lib/db';
import {aiEnv,requireAdmin,aiLimit,runProfile} from '@/lib/ai-server';
import {sealKey,validateProfile,ProviderError} from '@/lib/ai-core';
import {defaultStores,aggregate,today,type Store} from '@/lib/model';
import {anticipate,defaultOps} from '@/lib/operations';
import {demoOperationalData,demoOps} from '@/lib/demo-operations';
async function routing(){const row=await database().prepare("SELECT payload FROM settings WHERE id='ai_routing'").first<{payload:string}>();return row?JSON.parse(row.payload):{primary:'',fallback:'',allowFallback:false}}
export async function GET(req:Request){try{await requireAdmin(req);const [profiles,runs]=await Promise.all([database().prepare('SELECT id,name,provider,model,enabled,hint,updated_at FROM ai_profiles ORDER BY name').all(),database().prepare('SELECT * FROM ai_runs ORDER BY created_at DESC LIMIT 30').all()]);return json({profiles:profiles.results,runs:runs.results,routing:await routing(),vaultReady:!!aiEnv().AI_VAULT_KEY})}catch{return json({error:'Acesso de administrador necessário para configurar IA.'},403)}}
export async function POST(req:Request){try{await requireAdmin(req);if(Number(req.headers.get('content-length')||0)>12000)throw new Error('Solicitação muito extensa.');const raw=await req.text();if(raw.length>12000)throw new Error('Solicitação muito extensa.');const b=JSON.parse(raw),db=database();
 if(b.action==='profile'){const p=validateProfile(b.profile),id=p.id||crypto.randomUUID();if(typeof id!=='string'||id.length>80)throw new Error('Conexão inválida.');const old=await db.prepare('SELECT provider,cipher,hint FROM ai_profiles WHERE id=?').bind(id).first<any>();const secret=typeof b.key==='string'?b.key.trim():'';if(secret&&(secret.length<12||secret.length>2000||/\s/.test(secret)))throw new Error('Chave inválida.');if(!secret&&(!old||old.provider!==p.provider))throw new Error('Informe uma chave para este provedor.');const master=aiEnv().AI_VAULT_KEY;if(!master)throw new Error('Cofre de chaves indisponível.');const cipher=secret?await sealKey(secret,master,id+':'+p.provider):old.cipher,hint=secret?'••••'+secret.slice(-4):old.hint;await db.prepare('INSERT INTO ai_profiles(id,name,provider,model,enabled,cipher,hint,updated_at) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,provider=excluded.provider,model=excluded.model,enabled=excluded.enabled,cipher=excluded.cipher,hint=excluded.hint,updated_at=excluded.updated_at').bind(id,p.name,p.provider,p.model,p.enabled?1:0,cipher,hint,new Date().toISOString()).run();return json({ok:true,id})}
 if(b.action==='routing'){const v=b.value;if(!v||typeof v.primary!=='string'||typeof v.fallback!=='string'||typeof v.allowFallback!=='boolean'||v.primary&&v.primary===v.fallback||v.allowFallback&&(!v.primary||!v.fallback))throw new Error('Escolha conexões diferentes para principal e reserva.');for(const id of [v.primary,v.fallback].filter(Boolean))if(!await db.prepare('SELECT id FROM ai_profiles WHERE id=? AND enabled=1').bind(id).first())throw new Error('Selecione conexões ativas.');await db.prepare("INSERT INTO settings(id,payload) VALUES('ai_routing',?) ON CONFLICT(id) DO UPDATE SET payload=excluded.payload").bind(JSON.stringify({primary:v.primary,fallback:v.fallback,allowFallback:v.allowFallback})).run();return json({ok:true})}
 if(b.action==='delete'){const r=await routing();if(r.primary===b.id||r.fallback===b.id)throw new Error('Remova a conexão da principal e da reserva antes de excluir.');await db.prepare('DELETE FROM ai_profiles WHERE id=?').bind(String(b.id)).run();return json({ok:true})}
 if(b.action==='test'){await aiLimit();return json(await runProfile(String(b.id),'',true,'test'))}
 if(b.action!=='analyze')throw new Error('Operação desconhecida.');if(!['real','demo'].includes(b.dataset)||!validDate(b.end)||!validDate(b.start)||b.start>b.end||b.scope!=='totals'&&b.end>today())throw new Error('Período inválido.');const route=await routing();if(!route.primary)throw new Error('Cadastre uma conexão e escolha a principal.');const settings=await db.prepare("SELECT id,payload FROM settings WHERE id IN ('stores','operations')").all<{id:string;payload:string}>(),cfg=Object.fromEntries(settings.results.map(r=>[r.id,JSON.parse(r.payload)]));const stores:Store[]=cfg.stores||defaultStores;if(b.channel!=='all'&&!stores.some(s=>s.id===b.channel))throw new Error('Canal inválido.');const data=b.dataset==='demo'?demoOperationalData():await readRecords();let context='';if(b.scope==='totals'){if(b.dataset!=='real')throw new Error('Totalizações usam apenas dados importados.');const a=summarizeTotals(data.totals||[],stores,b.start,b.end,b.channel);if(!a.rows.length)throw new Error('Importe uma totalização com esse período exato.');context=JSON.stringify({dataset:'real',scope:'totals',start:b.start,end:b.end,metrics:{reportedValue:a.amount,netUnits:a.units,orders:null,ticket:null,margin:null},channels:a.channels.map(c=>({name:c.name,hasData:c.hasData,amount:c.hasData?c.amount:null,units:c.hasData?c.qty:null})),topProducts:a.products.slice(0,15),topVariants:a.variants.slice(0,30),categories:a.categories,negativeRows:a.negativeRows.length,financialAdjustments:a.adjustments.map(r=>({reference:r.reference,store:r.store,amount:r.amount})),limitations:['Totalização por referência para período declarado; não confirma fechamento completo.','Sem datas diárias, pedidos, estoque ou custos. Cor e tamanho somente quando informados no arquivo; nunca inferir detalhes ausentes.','Não estimar ticket por pedido, margem, demanda diária, reposição ou causa dos valores negativos.','Dados importados; Presence sem coleta automática ativa.']})}else{if(!data.sales.length)throw new Error('Importe vendas detalhadas ou use a análise em Vendas consolidadas.');const ops=b.dataset==='demo'?demoOps:cfg.operations||defaultOps,saved=await db.prepare('SELECT dataset,status,payload FROM actions').all(),a=aggregate(data,stores,b.start,b.end,b.channel),plan=anticipate(data,stores,b.end,ops,saved.results,b.dataset);
 context=JSON.stringify({dataset:b.dataset,start:b.start,end:b.end,channel:b.channel,metrics:{revenue:a.revenue,units:a.units,orders:a.orders,ticket:a.ticket,comparableChange:a.change,estimatedMargin:a.margin},channels:a.channels.map(s=>({name:s.name,status:s.status,revenue:s.revenue,units:s.units})),topProducts:a.ranked.slice(0,12),quality:plan.quality.map(q=>({store:q.name,status:q.status,stockDate:q.lastStock,missingControls:q.gaps.length,mismatches:q.mismatches.length,missingProducts:q.unknown})),decisions:plan.decisions.filter(d=>b.channel==='all'||d.to===b.channel||d.from===b.channel).slice(0,12),overdueOrders:plan.overdue.length,limitations:['Média histórica sem ajuste de sazonalidade.','Quantidades de regras determinísticas, sujeitas à revisão comercial.','Dados importados; Presence sem coleta automática ativa.','Custos atuais; margem não representa lucro líquido.']});}await aiLimit();try{return json({...await runProfile(route.primary,context,false,b.dataset),usedFallback:false})}catch(e){if(!(e instanceof ProviderError)||!e.retryable||!route.allowFallback||!route.fallback)throw e;return json({...await runProfile(route.fallback,context,false,b.dataset),usedFallback:true})}
 }catch(e){return json({error:e instanceof Error?e.message:'Não foi possível concluir a solicitação.'},400)}}
