'use client';
import {useMemo,useState,useId} from 'react';
import {ChevronDown,ChevronLeft,ChevronRight,Search,SlidersHorizontal,Layers,X,Grid3x3} from 'lucide-react';
import {catalogCategories,filterCatalog,gradeMatrix,groupCatalog,cellKey,searchKey,NOT_INFORMED,type CatalogRow,type CatalogModel} from '@/lib/catalog';
import {dayBR} from '@/lib/model';
const quantity=(n:number)=>n.toLocaleString('pt-BR',{maximumFractionDigits:3});
const currency=(n:number)=>n.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const PAGE=10,DETAIL=15;
type Mode='sales'|'stock';
const unitLabel=(mode:Mode)=>mode==='stock'?'saldo informado':'peças líquidas (QT)';
/** Category → model → color/size grade → detail. Sales show QT and VALOR; stock shows Saldo Base. Never mixed. */
export default function CatalogExplorer({rows,mode,title,context,category:controlled,onCategoryChange,initialModel=''}:{rows:CatalogRow[];mode:Mode;title?:string;context?:string;category?:string;onCategoryChange?:(v:string)=>void;initialModel?:string}){
 // Model keys are the cleaned reference (see groupCatalog), so a reference from another screen opens the same model.
 const [own,setOwn]=useState(''),[selected,setSelected]=useState(initialModel.trim().replace(/\s+/g,' ')),[query,setQuery]=useState(''),[modelQuery,setModelQuery]=useState(''),[sort,setSort]=useState(mode==='stock'?'qty':'amount'),[page,setPage]=useState(1),[expanded,setExpanded]=useState('');const labelId=useId();
 const category=controlled??own,setCategory=onCategoryChange??setOwn;
 const models=groupCatalog(rows),categories=catalogCategories(models).sort((a,b)=>mode==='sales'?b.amount-a.amount:b.qty-a.qty);
 // Filters that no longer exist after a period/unit change are reconciled instead of producing an empty contradictory view.
 const currentCategory=categories.some(c=>c.name===category)?category:'';
 const options=models.filter(m=>!currentCategory||m.category===currentCategory).sort((a,b)=>a.model.localeCompare(b.model,'pt-BR',{numeric:true})||a.reference.localeCompare(b.reference,'pt-BR',{numeric:true}));
 const currentModel=options.some(m=>m.key===selected)?selected:'';
 const visibleOptions=modelQuery.trim()?options.filter(m=>searchKey(`${m.model} ${m.reference}`).includes(searchKey(modelQuery.trim()))||m.key===currentModel):options;
 const filtered=filterCatalog(models,currentCategory,currentModel,query).sort((a,b)=>sort==='name'?a.model.localeCompare(b.model,'pt-BR',{numeric:true}):sort==='qty'?b.qty-a.qty:sort==='low'?a.qty-b.qty:b.amount-a.amount);
 const pages=Math.max(1,Math.ceil(filtered.length/PAGE)),currentPage=Math.min(page,pages),visible=filtered.slice((currentPage-1)*PAGE,currentPage*PAGE);
 const cents=filtered.reduce((a,m)=>a+Math.round(m.amount*100),0),qty=Math.round(filtered.reduce((a,m)=>a+m.qty,0)*1e6)/1e6,variants=filtered.reduce((a,m)=>a+m.variants,0);
 const filteredView=!!(currentCategory||currentModel||query);
 function chooseCategory(v:string){setCategory(v);setSelected('');setExpanded('');setModelQuery('');setPage(1)}
 function chooseModel(v:string){setSelected(v);setExpanded(v);setPage(1)}
 function clear(){chooseCategory('');setQuery('')}
 const maxCategory=Math.max(1,...categories.map(c=>Math.abs(mode==='sales'?c.amount:c.qty)));
 return <section className="panel catalog-explorer" aria-labelledby={labelId}>
  <div className="panel-head"><div><span className="eyebrow">EXPLORAR {mode==='stock'?'ESTOQUE':'VENDAS CONSOLIDADAS'}</span><h2 id={labelId}>{title||'Categorias, modelos e grade'}</h2><p>Escolha a categoria, depois o modelo, e abra a grade de cores × tamanhos.{context?` ${context}`:''}</p></div><span className="catalog-count"><Layers size={16}/>{models.length} modelos · {categories.length} categorias</span></div>
  {categories.length>0&&<div className="category-chips" role="group" aria-label="Categorias">{categories.map(c=><button key={c.name} type="button" aria-pressed={currentCategory===c.name} onClick={()=>chooseCategory(currentCategory===c.name?'':c.name)} className={'category-chip'+(currentCategory===c.name?' active':'')}><span className="chip-name">{c.name}</span><strong>{mode==='sales'?currency(c.amount):quantity(c.qty)}</strong><small>{c.models} {c.models===1?'modelo':'modelos'}{mode==='sales'?` · ${quantity(c.qty)} peças`:''}</small><span className="category-track" aria-hidden="true"><i style={{width:`${Math.max(0,Math.min(100,(mode==='sales'?c.amount:c.qty)/maxCategory*100))}%`}}/></span></button>)}</div>}
  <div className="catalog-controls">
   <label>Categoria<select value={currentCategory} onChange={e=>chooseCategory(e.target.value)}><option value="">Todas as categorias</option>{categories.map(c=><option key={c.name} value={c.name}>{c.name} ({c.models})</option>)}</select></label>
   <label>Modelo{options.length>15&&<input className="model-filter" value={modelQuery} onChange={e=>setModelQuery(e.target.value)} placeholder={`Filtrar ${options.length} modelos`} aria-label="Filtrar lista de modelos"/>}<select value={currentModel} onChange={e=>chooseModel(e.target.value)}><option value="">{currentCategory?`Todos de ${currentCategory} (${options.length})`:`Todos os modelos (${options.length})`}</option>{visibleOptions.map(m=><option key={m.key} value={m.key}>{m.model} · {m.reference||'sem referência'}</option>)}</select></label>
   <label>Ordenar<select value={sort} onChange={e=>{setSort(e.target.value);setPage(1)}}>{mode==='sales'&&<option value="amount">Maior valor</option>}<option value="qty">{mode==='stock'?'Maior saldo':'Mais peças (QT)'}</option>{mode==='stock'&&<option value="low">Menor saldo</option>}<option value="name">Nome do modelo</option></select></label>
   <label className="catalog-search">Buscar<span className="search-field"><Search size={17} aria-hidden="true"/><input type="search" value={query} onChange={e=>{setQuery(e.target.value);setPage(1)}} placeholder="Modelo, referência, cor, tamanho ou unidade"/></span></label>
  </div>
  <div className="catalog-context" aria-live="polite"><div className="context-pills"><span className="context-pill">{currentCategory||'Todas as categorias'}</span>{currentModel&&<span className="context-pill strong">{models.find(m=>m.key===currentModel)?.model} · {models.find(m=>m.key===currentModel)?.reference}</span>}{query&&<span className="context-pill">“{query}”</span>}</div><span className="context-totals">{filteredView?'Recorte filtrado':'Total do recorte'}: <strong>{filtered.length}</strong> {filtered.length===1?'modelo':'modelos'} · <strong>{variants}</strong> variações · <strong>{quantity(qty)}</strong> {unitLabel(mode)}{mode==='sales'&&<> · <strong>{currency(cents/100)}</strong></>}</span>{filteredView&&<button type="button" className="clear-button" onClick={clear}><X size={15}/>Limpar filtros</button>}</div>
  <div className="catalog-list">{visible.map((m,index)=>{const open=currentModel===m.key||expanded===m.key;return <ModelCard key={m.key} model={m} rank={(currentPage-1)*PAGE+index+1} mode={mode} open={open} onToggle={()=>{if(currentModel===m.key){setSelected('');setExpanded('')}else setExpanded(open?'':m.key)}}/>})}</div>
  {!filtered.length&&<div className="catalog-empty"><SlidersHorizontal size={25}/><h3>{rows.length?'Nenhum modelo encontrado':'Nenhum produto neste recorte'}</h3><p>{rows.length?'Tente outra categoria ou um termo de busca mais curto.':'Confira o período e a unidade ou importe uma planilha.'}</p>{rows.length>0&&<button type="button" className="btn secondary" onClick={clear}>Limpar filtros</button>}</div>}
  {filtered.length>PAGE&&<Pager label="modelos" page={currentPage} pages={pages} from={(currentPage-1)*PAGE+1} to={Math.min(currentPage*PAGE,filtered.length)} total={filtered.length} onPage={setPage}/>}
 </section>
}
function Pager({label,page,pages,from,to,total,onPage}:{label:string;page:number;pages:number;from:number;to:number;total:number;onPage:(n:number)=>void}){return <nav className="catalog-pagination" aria-label={`Paginação de ${label}`}><span>{from}–{to} de {total} {label}</span><div><button type="button" aria-label="Primeira página" disabled={page===1} onClick={()=>onPage(1)}>«</button><button type="button" aria-label="Página anterior" disabled={page===1} onClick={()=>onPage(page-1)}><ChevronLeft size={18}/></button><span aria-current="page">{page} / {pages}</span><button type="button" aria-label="Próxima página" disabled={page===pages} onClick={()=>onPage(page+1)}><ChevronRight size={18}/></button><button type="button" aria-label="Última página" disabled={page===pages} onClick={()=>onPage(pages)}>»</button></div></nav>}
function ModelCard({model:m,rank,mode,open,onToggle}:{model:CatalogModel;rank:number;mode:Mode;open:boolean;onToggle:()=>void}){const id=useId();return <article className={'model-card '+(open?'is-open':'')}><h3><button type="button" className="model-toggle" aria-expanded={open} aria-controls={id} onClick={onToggle}><span className="model-rank">{String(rank).padStart(2,'0')}</span><span className="model-name"><small>{m.category}{m.categoryStatus==='matched'?' · pelas totalizações':''} / <span className="ref">{m.reference||'sem referência'}</span></small><strong>{m.model}</strong><span>{m.variants} {m.variants===1?'variação':'variações'} · {m.colors} {m.colors===1?'cor':'cores'}{m.stores?` · ${m.stores} ${m.stores===1?'unidade':'unidades'}`:''}</span></span><span className="model-measure"><strong className={m.qty<0?'negative-value':''}>{quantity(m.qty)}</strong><small>{mode==='stock'?'saldo informado':'peças (QT)'}</small></span>{mode==='sales'&&<span className="model-measure money"><strong className={m.amount<0?'negative-value':''}>{currency(m.amount)}</strong><small>valor</small></span>}<ChevronDown size={20} className="expand-chevron" aria-hidden="true"/></button></h3><div id={id} hidden={!open}>{open&&<VariantDetail model={m} mode={mode}/>}</div></article>}
function VariantDetail({model:m,mode}:{model:CatalogModel;mode:Mode}){
 const [color,setColor]=useState(''),[size,setSize]=useState(''),[unit,setUnit]=useState(''),[page,setPage]=useState(1);
 const units=useMemo(()=>[...new Map(m.rows.filter(r=>r.store).map(r=>[r.store!,r.storeName||r.store!])).entries()].sort((a,b)=>a[1].localeCompare(b[1],'pt-BR')),[m.rows]);
 const scoped=useMemo(()=>unit?m.rows.filter(r=>r.store===unit):m.rows,[m.rows,unit]);
 const grid=useMemo(()=>gradeMatrix(scoped),[scoped]);
 const rows=scoped.filter(r=>(!color||r.color===color)&&(!size||r.size===size)).sort((a,b)=>a.color.localeCompare(b.color,'pt-BR',{numeric:true})||(grid.sizes.indexOf(a.size)-grid.sizes.indexOf(b.size))||(a.storeName||'').localeCompare(b.storeName||'','pt-BR'));
 const pages=Math.max(1,Math.ceil(rows.length/DETAIL)),current=Math.min(page,pages),visible=rows.slice((current-1)*DETAIL,current*DETAIL);
 const max=Math.max(1,...[...grid.cells.values()].map(c=>Math.abs(c.qty)));
 const rowQty=Math.round(rows.reduce((a,r)=>a+r.qty,0)*1e6)/1e6,rowAmount=rows.reduce((a,r)=>a+Math.round((r.amount||0)*100),0)/100;
 const colTotal=(s:string)=>Math.round(grid.colors.reduce((a,c)=>a+(grid.cells.get(cellKey(c,s))?.qty||0),0)*1e6)/1e6,rowTotal=(c:string)=>Math.round(grid.sizes.reduce((a,s)=>a+(grid.cells.get(cellKey(c,s))?.qty||0),0)*1e6)/1e6;
 const pick=(c:string,s:string)=>{const same=color===c&&size===s;setColor(same?'':c);setSize(same?'':s);setPage(1)};
 return <div className="variant-detail">
  <div className="variant-heading"><div><h4><Grid3x3 size={16}/> Grade de cores × tamanhos</h4><p>{mode==='stock'?'Saldo Base informado pela Presence':'QT líquida totalizada'} por variação{unit?` · ${units.find(u=>u[0]===unit)?.[1]}`:units.length>1?` · soma de ${units.length} unidades`:''}. Selecione uma célula para filtrar o detalhe.</p></div>{units.length>1&&<label className="unit-select">Unidade<select value={unit} onChange={e=>{setUnit(e.target.value);setColor('');setSize('');setPage(1)}}><option value="">Todas ({units.length})</option>{units.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label>}</div>
  <div className="grade-scroll"><table className="grade-table"><caption className="sr-only">Grade de {m.model}, referência {m.reference}: {mode==='stock'?'saldo':'peças'} por cor (linhas) e tamanho (colunas). Traço indica combinação ausente na fonte.</caption><thead><tr><th scope="col">Cor \ Tamanho</th>{grid.sizes.map(s=><th scope="col" key={s}>{s}{grid.codes.get(s)&&<small>grade {grid.codes.get(s)}</small>}</th>)}<th scope="col" className="total-col">Total</th></tr></thead>
   <tbody>{grid.colors.map(c=><tr key={c}><th scope="row">{c}</th>{grid.sizes.map(s=>{const cell=grid.cells.get(cellKey(c,s));const active=color===c&&size===s;return <td key={s}>{cell===undefined?<span className="absent" title="Combinação não presente na fonte" aria-label={`${c}, ${s}: sem registro`}>—</span>:<button type="button" className={'grade-cell'+(cell.qty<0?' negative-cell':cell.qty===0?' zero-cell':'')+(active?' selected-cell':'')} style={cell.qty>0?{'--heat':(.08+.5*cell.qty/max).toFixed(3)} as React.CSSProperties:undefined} aria-pressed={active} aria-label={`${c}, tamanho ${s}: ${quantity(cell.qty)}${mode==='sales'?`, ${currency(cell.amount)}`:''}. ${active?'Remover filtro':'Filtrar detalhe'}.`} onClick={()=>pick(c,s)}>{quantity(cell.qty)}</button>}</td>})}<td className="total-col tabular">{quantity(rowTotal(c))}</td></tr>)}</tbody>
   <tfoot><tr><th scope="row">Total</th>{grid.sizes.map(s=><td key={s} className="tabular">{quantity(colTotal(s))}</td>)}<td className="total-col tabular"><strong>{quantity(Math.round(scoped.reduce((a,r)=>a+r.qty,0)*1e6)/1e6)}</strong></td></tr></tfoot></table></div>
  <p className="grade-legend"><span><i className="lg-absent">—</i> sem registro na fonte</span><span><i className="lg-zero">0</i> zero informado</span><span><i className="lg-neg">−</i> valor negativo preservado</span>{(grid.colors.includes(NOT_INFORMED)||grid.sizes.includes(NOT_INFORMED))&&<span>“{NOT_INFORMED}” = arquivo sem cor/tamanho (formato antigo); não é distribuído entre variações.</span>}</p>
  <div className="variant-filters"><label>Cor<select value={color} onChange={e=>{setColor(e.target.value);setPage(1)}}><option value="">Todas as cores</option>{grid.colors.map(c=><option key={c} value={c}>{c}</option>)}</select></label><label>Tamanho<select value={size} onChange={e=>{setSize(e.target.value);setPage(1)}}><option value="">Todos os tamanhos</option>{grid.sizes.map(s=><option key={s} value={s}>{s}</option>)}</select></label>{(color||size)&&<button type="button" className="text-button" onClick={()=>{setColor('');setSize('');setPage(1)}}><X size={14}/>Voltar à grade completa</button>}<span className="detail-count" aria-live="polite">{rows.length} {rows.length===1?'registro':'registros'} · {quantity(rowQty)}{mode==='sales'?` · ${currency(rowAmount)}`:''}</span></div>
  <div className="table-scroll"><table className="variant-table"><thead><tr><th scope="col">Cor</th><th scope="col">Tamanho</th>{units.length>0&&<th scope="col">Unidade</th>}<th scope="col" className="right">{mode==='stock'?'Saldo informado':'QT'}</th>{mode==='sales'&&<th scope="col" className="right">Valor</th>}<th scope="col">{mode==='stock'?'Data da posição':'Período'}</th><th scope="col">Origem</th></tr></thead><tbody>{visible.map(r=><tr key={r.id}><td>{r.color}{r.rawColor&&r.rawColor.trim()!==r.color&&<small className="block muted" title="Valor original">{r.rawColor.trim()}</small>}</td><td>{r.size}{r.sizeCode&&<small className="block muted">grade {r.sizeCode}</small>}</td>{units.length>0&&<td>{r.storeName||'—'}</td>}<td className={'right tabular '+(r.qty<0?'negative-value':'')}>{quantity(r.qty)}{mode==='stock'&&r.qty<0&&<small className="block">Saldo negativo</small>}{mode==='stock'&&!Number.isInteger(r.qty)&&<small className="block muted">Fracionado</small>}</td>{mode==='sales'&&<td className={'right tabular '+((r.amount||0)<0?'negative-value':'')}>{currency(r.amount||0)}</td>}<td className="muted">{mode==='stock'?(r.date?dayBR(r.date):'—'):r.period?r.period.split('|').map(dayBR).join(' a '):'—'}</td><td className="muted small-text">{mode==='stock'?'Saldo Estoque · Presence':r.origin||'Totalização'}</td></tr>)}</tbody></table></div>
  {rows.length===0&&<p className="empty-inline">Nenhuma variação com esses filtros.</p>}
  {pages>1&&<Pager label="registros" page={current} pages={pages} from={(current-1)*DETAIL+1} to={Math.min(current*DETAIL,rows.length)} total={rows.length} onPage={setPage}/>}
 </div>
}
