'use client';
import {useMemo,useState,useId} from 'react';
import {Lightbulb,Search,Check,X,CircleCheckBig,SlidersHorizontal} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {kindLabels,priorityLabels,type Finding,type FindingKind,type Priority} from '@/lib/findings';
import {searchKey} from '@/lib/catalog';
import {dayBR} from '@/lib/model';
const statusLabels:Record<string,string>={pending:'A avaliar',approved:'Aprovada',done:'Concluída',dismissed:'Descartada'};
type Saved={status:string;owner?:string;due?:string;note?:string;updatedAt?:string};
type Card=Finding&Saved;
const PAGE=12;
const groupOrder:FindingKind[]=['ruptura','realocar','reposicao','parado','negativo','dados'];
const groupTitles:Record<FindingKind,string>={ruptura:'Transferir para cobrir falta',realocar:'Levar estoque parado para onde vende',reposicao:'Repor: sem saldo livre na rede',parado:'Estoque parado',negativo:'Saldo negativo para conferir',dados:'Qualidade dos dados'};
const rank={alta:0,media:1,baixa:2};
function groupsOf<T extends {kind:FindingKind}>(items:T[]){return groupOrder.map(k=>[k,items.filter(i=>i.kind===k)] as [FindingKind,T[]]).filter(([,i])=>i.length)}
/** Findings as cards: what we saw → what to do. Approving records a decision; nothing runs in Presence. */
export default function FindingsBoard({findings:all,saved,channel,onSave,kinds,eyebrow='ACHADOS E SUGESTÕES',title='O que olhar primeiro',description='Cruzamento das vendas consolidadas com o saldo de cada unidade. Cada card mostra a evidência e uma sugestão; aprovar registra a decisão, sem executar nada na Presence.'}:{findings:Finding[];saved:{dataset:string;status:string;payload:string;updated_at:string}[];channel:string;onSave:(a:Card,status:string)=>Promise<void>;kinds?:FindingKind[];eyebrow?:string;title?:string;description?:string}){
 const findings=kinds?all.filter(f=>kinds.includes(f.kind)):all;
 const titleId=useId();const [priority,setPriority]=useState<Priority|''>(''),[kind,setKind]=useState(''),[status,setStatus]=useState('open'),[query,setQuery]=useState(''),[limit,setLimit]=useState(PAGE),[edit,setEdit]=useState<Card|null>(null),[busy,setBusy]=useState('');
 const history=useMemo(()=>new Map(saved.filter(s=>s.dataset==='real').map(s=>{const p=JSON.parse(s.payload);return [p.id,{...p,status:s.status,updatedAt:s.updated_at}]})),[saved]);
 const cards:Card[]=findings.map(f=>{const h=history.get(f.id);return {...f,status:h?.status||'pending',owner:h?.owner,due:h?.due,note:h?.note,updatedAt:h?.updatedAt}}).filter(c=>channel==='all'||c.store==='all'||c.store===channel||c.from===channel||c.to===channel);
 const openCards=cards.filter(c=>c.status==='pending'||c.status==='approved');
 const visible=cards.filter(c=>(status==='open'?c.status==='pending'||c.status==='approved':status==='all'||c.status===status)&&(!priority||c.priority===priority)&&(!kind||c.kind===kind)&&(!query.trim()||searchKey(`${c.title} ${c.evidence.join(' ')} ${c.storeName}`).includes(searchKey(query.trim()))));
 visible.sort((a,b)=>groupOrder.indexOf(a.kind)-groupOrder.indexOf(b.kind)||rank[a.priority]-rank[b.priority]);
 const count=(p:Priority)=>openCards.filter(c=>c.priority===p).length;
 async function save(c:Card,s:string){setBusy(c.id);try{await onSave(c,s)}finally{setBusy('')}}
 const filtered=!!(priority||kind||query||status!=='open');
 return <section className="findings-board" aria-labelledby={titleId}>
  <div className="findings-head"><div><span className="eyebrow">{eyebrow}</span><h2 id={titleId}>{title}</h2><p>{description}</p></div></div>
  <div className="priority-strip" role="group" aria-label="Filtrar por prioridade">{(['alta','media','baixa'] as Priority[]).map(p=><button type="button" key={p} aria-pressed={priority===p} className={'priority-tile '+p+(priority===p?' active':'')} onClick={()=>{setPriority(priority===p?'':p);setLimit(PAGE)}}><strong>{count(p)}</strong><span>Prioridade {priorityLabels[p].toLowerCase()}</span></button>)}<div className="priority-tile neutral"><strong>{cards.filter(c=>c.status==='done').length}</strong><span>Concluídas</span></div></div>
  <div className="findings-filters"><label className="catalog-search">Buscar<span className="search-field"><Search size={16} aria-hidden="true"/><input type="search" value={query} onChange={e=>{setQuery(e.target.value);setLimit(PAGE)}} placeholder="Modelo, referência ou unidade"/></span></label><label>Tipo<select value={kind} onChange={e=>{setKind(e.target.value);setLimit(PAGE)}}><option value="">Todos os tipos</option>{Object.entries(kindLabels).filter(([v])=>!kinds||kinds.includes(v as FindingKind)).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Situação<select value={status} onChange={e=>{setStatus(e.target.value);setLimit(PAGE)}}><option value="open">Em aberto</option><option value="all">Todas</option>{Object.entries(statusLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>{filtered&&<button type="button" className="clear-button" onClick={()=>{setPriority('');setKind('');setQuery('');setStatus('open');setLimit(PAGE)}}><X size={14}/>Limpar filtros</button>}<span className="detail-count" aria-live="polite">{visible.length} {visible.length===1?'achado':'achados'}</span></div>
  {!findings.length?<div className="catalog-empty"><SlidersHorizontal size={24}/><h3>Nenhum achado ainda</h3><p>Importe a totalização de vendas e o Saldo Estoque das unidades para cruzar vendas e saldo.</p></div>:!visible.length?<div className="catalog-empty"><Check size={24}/><h3>Nada neste filtro</h3><p>Troque a prioridade, o tipo ou a situação.</p></div>:
  <div className="fgroups">{groupsOf(visible.slice(0,limit)).map(([kind,items])=><section key={kind} className="fgroup"><h3 className="fgroup-title">{groupTitles[kind]}<span>{visible.filter(c=>c.kind===kind).length}</span></h3><div className="fcard-grid">{items.map(c=><article key={c.id} className={'fcard '+c.priority+(c.status==='done'||c.status==='dismissed'?' closed':'')}>
   <div className="fcard-top"><span className={'priority-pill '+c.priority}>{priorityLabels[c.priority]}</span>{c.store!=='all'&&<span className="fcard-unit">{c.storeName.split(' · ')[0]}</span>}</div>
   <h4>{c.title}</h4>{c.subtitle&&<p className="fcard-sub">{c.subtitle}</p>}
   {c.metrics&&c.metrics.length>0&&<dl className="fcard-metrics">{c.metrics.map((m,i)=><div key={i} className={m.tone||''}><dt>{m.label}</dt><dd>{m.value}</dd></div>)}</dl>}
   <div className="fcard-action"><Lightbulb size={16} aria-hidden="true"/><strong>{c.action||c.suggestion}</strong></div>
   <details className="fcard-more"><summary>Ver detalhes</summary><ul>{c.evidence.map((e,i)=><li key={i}>{e}</li>)}</ul>{c.action&&<p>{c.suggestion}</p>}</details>
   <footer><span className={'badge '+(c.status==='approved'?'ok':c.status==='done'?'planned':c.status==='dismissed'?'outdated':'risk')}>{statusLabels[c.status]}</span>{(c.owner||c.due)&&<small>{c.owner||'Sem responsável'}{c.due?` · até ${dayBR(c.due)}`:''}</small>}
    <div className="finding-actions">{c.status==='pending'&&<button type="button" className="btn primary sm" disabled={busy===c.id} onClick={()=>setEdit({...c,status:'approved'})}><Check size={15}/>Aprovar</button>}{c.status==='approved'&&<button type="button" className="btn primary sm" disabled={busy===c.id} onClick={()=>save(c,'done')}><CircleCheckBig size={15}/>Concluir</button>}{(c.status==='pending'||c.status==='approved')&&<button type="button" className="btn secondary sm" disabled={busy===c.id} onClick={()=>save(c,'dismissed')}>Descartar</button>}<button type="button" className="text-button" onClick={()=>setEdit({...c})}>Editar</button></div></footer>
  </article>)}</div></section>)}</div>}
  {visible.length>limit&&<div className="show-more"><button type="button" className="btn secondary" onClick={()=>setLimit(limit+PAGE)}>Mostrar mais {Math.min(PAGE,visible.length-limit)} de {visible.length-limit}</button></div>}
  <Dialog open={!!edit} onOpenChange={v=>!v&&setEdit(null)}><DialogContent className="v2-dialog"><DialogHeader><DialogTitle>{edit?.status==='approved'&&history.get(edit.id)?.status!=='approved'?'Aprovar ação':'Detalhes da ação'}</DialogTitle><DialogDescription>{edit?.title}</DialogDescription></DialogHeader>{edit&&<form className="v2-stack" onSubmit={async e=>{e.preventDefault();await save(edit,edit.status);setEdit(null)}}><div className="finding-suggestion"><Lightbulb size={16}/><p>{edit.suggestion}</p></div><label>Situação<select value={edit.status} onChange={e=>setEdit({...edit,status:e.target.value})}>{Object.entries(statusLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Responsável<input maxLength={100} value={edit.owner||''} onChange={e=>setEdit({...edit,owner:e.target.value})} placeholder="Quem vai executar"/></label><label>Prazo<input type="date" value={edit.due||''} onChange={e=>setEdit({...edit,due:e.target.value})}/></label><label>Nota<textarea rows={3} maxLength={1000} value={edit.note||''} onChange={e=>setEdit({...edit,note:e.target.value})} placeholder="Combinado com a loja, quantidade ajustada, motivo do descarte…"/></label><button className="btn primary" type="submit" disabled={busy===edit.id}>{busy===edit.id?'Salvando…':'Salvar'}</button></form>}</DialogContent></Dialog>
 </section>
}
