'use client';
import {useMemo,useState,useId,useEffect} from 'react';
import {Lightbulb,Search,Check,X,CircleCheckBig,SlidersHorizontal,LayoutGrid,List} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {kindLabels,priorityLabels,type Finding,type FindingKind,type Priority} from '@/lib/findings';
import {searchKey} from '@/lib/catalog';
import {dayBR} from '@/lib/model';
const statusLabels:Record<string,string>={pending:'A avaliar',approved:'Aprovada',done:'Concluída',dismissed:'Descartada'};
type Baseline={value:number|null;date:string;label:string};
type Saved={status:string;owner?:string;due?:string;note?:string;updatedAt?:string;baseline?:Baseline;approvedAt?:string;executedAt?:string;changed?:boolean};
const num=(v:number|null)=>v===null?'não consta':v.toLocaleString('pt-BR',{maximumFractionDigits:1});
type Card=Finding&Saved;
const groupOrder:FindingKind[]=['ruptura','realocar','reposicao','desempenho','grade','ecommerce','mix','ranking','parado','compras','negativo','dados'];
const groupTitles:Record<FindingKind,string>={ruptura:'Transferir para cobrir falta',realocar:'Levar estoque parado para onde vende',reposicao:'Repor: sem saldo livre na rede',parado:'Estoque parado',negativo:'Saldo negativo para conferir',dados:'Qualidade dos dados',desempenho:'Desempenho de vendas',mix:'Categorias e modelos',ranking:'Ranking e mudanças',grade:'Estoque e grade',ecommerce:'E-commerce',compras:'Compras'};
const rank={alta:0,media:1,baixa:2};
const urlParam=(k:string)=>typeof window==='undefined'?null:new URLSearchParams(window.location.search).get(k);
function groupsOf<T extends {kind:FindingKind}>(items:T[]){return groupOrder.map(k=>[k,items.filter(i=>i.kind===k)] as [FindingKind,T[]]).filter(([,i])=>i.length)}
/** Findings as cards: what we saw → what to do. Approving records a decision; nothing runs in Presence. */
export default function FindingsBoard({findings:all,saved,channel,onSave,kinds,observe,eyebrow='ACHADOS E SUGESTÕES',title='O que olhar primeiro',description='Cruzamento das vendas consolidadas com o saldo de cada unidade. Cada card mostra a evidência e uma sugestão; aprovar registra a decisão, sem executar nada na Presence.'}:{findings:Finding[];saved:{dataset:string;status:string;payload:string;updated_at:string}[];channel:string;onSave:(a:Card,status:string)=>Promise<void>;kinds?:FindingKind[];observe?:(store:string,reference:string)=>{value:number|null;date:string};eyebrow?:string;title?:string;description?:string}){
 const findings=kinds?all.filter(f=>kinds.includes(f.kind)):all;
 const titleId=useId();const [priority,setPriority]=useState<Priority|''>(()=>{const p=urlParam('p');return p==='alta'||p==='media'||p==='baixa'?p:''}),[kind,setKind]=useState(()=>{const k=urlParam('k');return k&&Object.hasOwn(kindLabels,k)?k:''}),[status,setStatus]=useState('open'),[query,setQuery]=useState(''),[expanded,setExpanded]=useState<Set<string>>(new Set()),[view,setView]=useState<'cards'|'list'>(()=>{try{return typeof window!=='undefined'&&localStorage.getItem('mondepars-findings-view')==='list'?'list':'cards'}catch{return 'cards'}}),[edit,setEdit]=useState<Card|null>(null),[busy,setBusy]=useState('');
 const history=useMemo(()=>new Map(saved.filter(s=>s.dataset==='real').map(s=>{const p=JSON.parse(s.payload);return [p.id,{...p,status:s.status,updatedAt:s.updated_at}]})),[saved]);
 // A closed decision reopens when the numbers behind it changed (different fingerprint).
 const cards:Card[]=findings.map(f=>{const h=history.get(f.id),changed=!!(h?.fingerprint&&f.fingerprint&&h.fingerprint!==f.fingerprint);const status=h?.status||'pending';return {...f,status:changed&&(status==='done'||status==='dismissed')?'pending':status,changed,owner:h?.owner,due:h?.due,note:h?.note,updatedAt:h?.updatedAt,baseline:h?.baseline,approvedAt:h?.approvedAt,executedAt:h?.executedAt}}).filter(c=>channel==='all'||c.store==='all'||c.store===channel||c.from===channel||c.to===channel);
 const openCards=cards.filter(c=>c.status==='pending'||c.status==='approved');
 const visible=cards.filter(c=>(status==='open'?c.status==='pending'||c.status==='approved':status==='all'||c.status===status)&&(!priority||c.priority===priority)&&(!kind||c.kind===kind)&&(!query.trim()||searchKey(`${c.title} ${c.evidence.join(' ')} ${c.storeName}`).includes(searchKey(query.trim()))));
 visible.sort((a,b)=>groupOrder.indexOf(a.kind)-groupOrder.indexOf(b.kind)||rank[a.priority]-rank[b.priority]);
 const count=(p:Priority)=>openCards.filter(c=>c.priority===p).length;
 // Approval stores the follow-up baseline; completion stores the execution date. Later readings show the observed evolution.
 async function save(c:Card,s:string){setBusy(c.id);const now=new Date().toISOString();const extra:Partial<Saved>=s==='approved'&&!c.baseline&&c.follow?{baseline:{value:c.follow.value,date:c.follow.date,label:c.follow.label},approvedAt:now}:s==='done'&&!c.executedAt?{executedAt:now}:{};try{await onSave({...c,...extra,changed:undefined},s)}finally{setBusy('')}}
 const filtered=!!(priority||kind||query||status!=='open');
 // Priority and type filters live in the URL (?p=&k=, read on mount) so a filtered view can be shared or restored with Back.
 useEffect(()=>{const q=new URLSearchParams(window.location.search);if(priority)q.set('p',priority);else q.delete('p');if(kind)q.set('k',kind);else q.delete('k');const n='?'+q.toString();if(n!==window.location.search)window.history.replaceState(null,'',n)},[priority,kind]);
 const toggle=(k:string)=>setExpanded(old=>{const n=new Set(old);if(n.has(k))n.delete(k);else n.add(k);return n});
 const jump=(k:string)=>{setExpanded(old=>new Set(old).add(k));document.getElementById(`${titleId}-${k}`)?.scrollIntoView({behavior:'smooth',block:'start'})};
 const [narrow,setNarrow]=useState(false);useEffect(()=>{const m=window.matchMedia('(max-width: 767px)');const f=()=>setNarrow(m.matches);f();m.addEventListener('change',f);return()=>m.removeEventListener('change',f)},[]);
 const pickView=(v:'cards'|'list')=>{setView(v);try{localStorage.setItem('mondepars-findings-view',v)}catch{}};
 const buttons=(c:Card)=><>{c.status==='pending'&&<button type="button" className="btn primary sm" disabled={busy===c.id} onClick={()=>setEdit({...c,status:'approved'})}><Check size={15}/>Aprovar</button>}{c.status==='approved'&&<button type="button" className="btn primary sm" disabled={busy===c.id} onClick={()=>save(c,'done')}><CircleCheckBig size={15}/>Concluir</button>}{(c.status==='pending'||c.status==='approved')&&<button type="button" className="btn secondary sm" disabled={busy===c.id} onClick={()=>save(c,'dismissed')}>Descartar</button>}</>;
 const renderRow=(c:Card)=><li key={c.id} className={'frow '+c.priority+(c.status==='done'||c.status==='dismissed'?' closed':'')}><span className={'priority-pill '+c.priority}>{priorityLabels[c.priority]}</span><span className="frow-unit">{c.store==='all'?'Rede':c.storeName.split(' · ')[0]}</span><div className="frow-main"><b>{c.title}</b><small>{c.action||c.suggestion}</small></div><span className={'badge '+(c.status==='approved'?'ok':c.status==='done'?'planned':c.status==='dismissed'?'outdated':'risk')}>{statusLabels[c.status]}</span><div className="finding-actions">{buttons(c)}<button type="button" className="text-button" onClick={()=>setEdit({...c})}>Detalhes</button></div></li>;
 const renderCard=(c:Card)=><article key={c.id} className={'fcard '+c.priority+(c.status==='done'||c.status==='dismissed'?' closed':'')}>
   <div className="fcard-top"><span className={'priority-pill '+c.priority}>{priorityLabels[c.priority]}</span>{c.store!=='all'&&<span className="fcard-unit">{c.storeName.split(' · ')[0]}</span>}</div>
   <h4>{c.title}</h4>{c.subtitle&&<p className="fcard-sub">{c.subtitle}</p>}
   {c.metrics&&c.metrics.length>0&&<dl className="fcard-metrics">{c.metrics.map((m,i)=><div key={i} className={m.tone||''}><dt>{m.label}</dt><dd>{m.value}</dd></div>)}</dl>}
   <div className="fcard-action"><Lightbulb size={16} aria-hidden="true"/><strong>{c.action||c.suggestion}</strong></div>
   {c.changed&&<p className="fcard-changed">Os números mudaram desde a última decisão.</p>}
   {c.baseline&&(c.status==='approved'||c.status==='done')&&(()=>{const now=observe&&c.follow?observe(c.follow.store,c.follow.reference):null;return <p className="fcard-follow"><b>Acompanhamento:</b> {c.baseline.label} {num(c.baseline.value)} em {dayBR(c.baseline.date)}{now&&now.date&&now.date!==c.baseline.date?<> → {num(now.value)} em {dayBR(now.date)}</>:' · aguardando nova posição'}. Evolução observada, não prova de efeito da ação.</p>})()}
   <details className="fcard-more"><summary>Ver detalhes</summary>
    {c.fact&&<p className="fcard-label"><b>Fato</b> {c.fact}</p>}
    <ul>{c.evidence.map((e,i)=><li key={i}>{e}</li>)}</ul>
    {c.hypotheses&&c.hypotheses.length>0&&<div className="fcard-block"><b>Hipóteses (não comprovadas)</b><ul>{c.hypotheses.map((h,i)=><li key={i}>{h.text}{h.support?` Apoio: ${h.support}`:''}{h.validateWith.length?` Validar com: ${h.validateWith.join(', ')}.`:''}</li>)}</ul></div>}
    <p className="fcard-label"><b>Recomendação</b> {c.suggestion}</p>
    {c.limitations&&c.limitations.length>0&&<div className="fcard-block"><b>Limitações</b><ul>{c.limitations.map((l,i)=><li key={i}>{l}</li>)}</ul></div>}
    {c.scope&&<p className="fcard-scope">{[c.scope.period&&`Período ${c.scope.period}`,c.scope.compare&&`comparado a ${c.scope.compare}`,c.quality&&`qualidade dos dados: ${c.quality.level}`].filter(Boolean).join(' · ')}{c.priorityReasons?.length?` · Prioridade: ${c.priorityReasons.join('; ')}`:''}</p>}
   </details>
   <footer><span className={'badge '+(c.status==='approved'?'ok':c.status==='done'?'planned':c.status==='dismissed'?'outdated':'risk')}>{statusLabels[c.status]}</span>{(c.owner||c.due)&&<small>{c.owner||'Sem responsável'}{c.due?` · até ${dayBR(c.due)}`:''}</small>}
    <div className="finding-actions">{c.status==='pending'&&<button type="button" className="btn primary sm" disabled={busy===c.id} onClick={()=>setEdit({...c,status:'approved'})}><Check size={15}/>Aprovar</button>}{c.status==='approved'&&<button type="button" className="btn primary sm" disabled={busy===c.id} onClick={()=>save(c,'done')}><CircleCheckBig size={15}/>Concluir</button>}{(c.status==='pending'||c.status==='approved')&&<button type="button" className="btn secondary sm" disabled={busy===c.id} onClick={()=>save(c,'dismissed')}>Descartar</button>}<button type="button" className="text-button" onClick={()=>setEdit({...c})}>Editar</button></div></footer>
  </article>;

 return <section className="findings-board" aria-labelledby={titleId}>
  <div className="findings-head"><div><span className="eyebrow">{eyebrow}</span><h2 id={titleId}>{title}</h2><p>{description}</p></div></div>
  <div className="priority-strip" role="group" aria-label="Filtrar por prioridade">{(['alta','media','baixa'] as Priority[]).map(p=><button type="button" key={p} aria-pressed={priority===p} className={'priority-tile '+p+(priority===p?' active':'')} onClick={()=>{setPriority(priority===p?'':p)}}><strong>{count(p)}</strong><span>Prioridade {priorityLabels[p].toLowerCase()}</span></button>)}<div className="priority-tile neutral"><strong>{cards.filter(c=>c.status==='done').length}</strong><span>Concluídas</span></div></div>
  <div className="findings-filters"><label className="catalog-search">Buscar<span className="search-field"><Search size={16} aria-hidden="true"/><input type="search" value={query} onChange={e=>{setQuery(e.target.value)}} placeholder="Modelo, referência ou unidade"/></span></label><label>Tipo<select value={kind} onChange={e=>{setKind(e.target.value)}}><option value="">Todos os tipos</option>{Object.entries(kindLabels).filter(([v])=>!kinds||kinds.includes(v as FindingKind)).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Situação<select value={status} onChange={e=>{setStatus(e.target.value)}}><option value="open">Em aberto</option><option value="all">Todas</option>{Object.entries(statusLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>{filtered&&<button type="button" className="clear-button" onClick={()=>{setPriority('');setKind('');setQuery('');setStatus('open')}}><X size={14}/>Limpar filtros</button>}<span className="detail-count" aria-live="polite">{visible.length} {visible.length===1?'achado':'achados'}</span></div>
  {visible.length>0&&<div className="fgroup-nav"><nav aria-label="Ir para o grupo">{groupsOf(visible).map(([k,items])=><button type="button" key={k} className="chip" onClick={()=>jump(k)}>{groupTitles[k]} <b>{items.length}</b></button>)}</nav><div className="seg" role="group" aria-label="Formato"><button type="button" aria-pressed={view==='cards'} className={view==='cards'?'on':''} onClick={()=>pickView('cards')}><LayoutGrid size={14}/>Cards</button><button type="button" aria-pressed={view==='list'} className={view==='list'?'on':''} onClick={()=>pickView('list')}><List size={14}/>Lista</button></div></div>}
  {!findings.length?<div className="catalog-empty"><SlidersHorizontal size={24}/><h3>Nenhum achado ainda</h3><p>Importe a totalização de vendas e o Saldo Estoque das unidades para cruzar vendas e saldo.</p></div>:!visible.length?<div className="catalog-empty"><Check size={24}/><h3>Nada neste filtro</h3><p>Troque a prioridade, o tipo ou a situação.</p></div>:
  <div className="fgroups">{groupsOf(visible).map(([kind,items])=>{const low=!priority&&items.every(c=>c.priority==='baixa'),max=low?0:view==='cards'?(narrow?1:3):5,open=expanded.has(kind)||items.length<=max;return <section key={kind} id={`${titleId}-${kind}`} className="fgroup"><h3 className="fgroup-title">{groupTitles[kind]}<span>{items.length}</span></h3>
   {(open||max>0)&&(view==='cards'?<div className="fcard-grid">{(open?items:items.slice(0,max)).map(renderCard)}</div>:<ul className="frows">{(open?items:items.slice(0,max)).map(renderRow)}</ul>)}
   {items.length>max&&<button type="button" className="fgroup-more" aria-expanded={open} onClick={()=>toggle(kind)}>{open?'Mostrar menos':low?`Ver ${items.length} de prioridade baixa`:`Ver todos (${items.length})`}</button>}</section>})}</div>}
  <Dialog open={!!edit} onOpenChange={v=>!v&&setEdit(null)}><DialogContent className="v2-dialog"><DialogHeader><DialogTitle>{edit?.status==='approved'&&history.get(edit.id)?.status!=='approved'?'Aprovar ação':'Detalhes da ação'}</DialogTitle><DialogDescription>{edit?.title}</DialogDescription></DialogHeader>{edit&&<form className="v2-stack" onSubmit={async e=>{e.preventDefault();await save(edit,edit.status);setEdit(null)}}><div className="finding-suggestion"><Lightbulb size={16}/><p>{edit.suggestion}</p></div><label>Situação<select value={edit.status} onChange={e=>setEdit({...edit,status:e.target.value})}>{Object.entries(statusLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Responsável<input maxLength={100} value={edit.owner||''} onChange={e=>setEdit({...edit,owner:e.target.value})} placeholder="Quem vai executar"/></label><label>Prazo<input type="date" value={edit.due||''} onChange={e=>setEdit({...edit,due:e.target.value})}/></label><label>Nota<textarea rows={3} maxLength={1000} value={edit.note||''} onChange={e=>setEdit({...edit,note:e.target.value})} placeholder="Combinado com a loja, quantidade ajustada, motivo do descarte…"/></label><button className="btn primary" type="submit" disabled={busy===edit.id}>{busy===edit.id?'Salvando…':'Salvar'}</button></form>}</DialogContent></Dialog>
 </section>
}
