import {database} from './db';
import {requireAdmin as requireAdminUser} from './auth';
import {invokeProvider,openKey,ProviderError,chatWithTools,type Profile,type Purpose,type ChatMessage,type ChatTool} from './ai-core';
export function aiEnv(){return {AI_VAULT_KEY:process.env.AI_VAULT_KEY,APP_ADMIN_EMAIL:process.env.APP_ADMIN_EMAIL}}
export async function requireAdmin(req:Request){try{return await requireAdminUser(req)}catch{throw new Error('A configuração de IA está disponível apenas para o administrador.')}}
export async function aiLimit(){const hour=new Date().toISOString().slice(0,13);const row=await database().prepare('INSERT INTO ai_quota(id,count) VALUES(?,1) ON CONFLICT(id) DO UPDATE SET count=ai_quota.count+1 RETURNING count').bind(hour).first<{count:number}>();const limit=aiHourlyLimit();if(!row||row.count>limit)throw new Error(`Limite de ${limit} solicitações de IA por hora atingido. Tente na próxima hora.`);}
/** Site-wide cap per hour; AI_HOURLY_LIMIT overrides the default. */
export function aiHourlyLimit(){const n=Number(process.env.AI_HOURLY_LIMIT);return Number.isInteger(n)&&n>0&&n<=1000?n:30}
export async function runProfile(id:string,context:string,test:boolean,dataset:string,purpose:Purpose='analysis'){const db=database();const p=await db.prepare('SELECT * FROM ai_profiles WHERE id=? AND enabled=1').bind(id).first<any>();if(!p)throw new Error('Conexão indisponível. Selecione uma conexão ativa.');const master=aiEnv().AI_VAULT_KEY;if(!master)throw new Error('Cofre de chaves indisponível.');const begin=Date.now(),runId=crypto.randomUUID();let result;try{const key=await openKey(p.cipher,master,p.id+':'+p.provider);result=await invokeProvider(p as Profile,key,context,test,fetch,purpose)}catch(e){const message=e instanceof ProviderError?e.message:'Não foi possível abrir a credencial. Cadastre a chave novamente.';await db.prepare('INSERT INTO ai_runs(id,profile_id,provider,model,dataset,purpose,created_at,status,duration_ms,input_tokens,output_tokens,output) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)').bind(runId,p.id,p.provider,p.model,dataset,test?'test':purpose,new Date().toISOString(),'failed',Date.now()-begin,null,null,message).run();if(e instanceof ProviderError)throw e;throw new Error(message)}
 await db.prepare('INSERT INTO ai_runs(id,profile_id,provider,model,dataset,purpose,created_at,status,duration_ms,input_tokens,output_tokens,output) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)').bind(runId,p.id,p.provider,p.model,dataset,test?'test':purpose,new Date().toISOString(),'succeeded',Date.now()-begin,result.input,result.output,result.text).run();return {id:runId,provider:p.provider,model:p.model,profile:p.name,...result};}
export async function routing():Promise<{primary:string;fallback:string;allowFallback:boolean}>{const row=await database().prepare("SELECT payload FROM settings WHERE id='ai_routing'").first<{payload:string}>();return row?JSON.parse(row.payload):{primary:'',fallback:'',allowFallback:false}}
/** Primary connection, then the fallback on retryable provider errors (same rule as before). Counts toward the hourly cap. */
export async function generate(context:string,dataset:string,purpose:Purpose){const route=await routing();if(!route.primary)throw new Error('Nenhuma conexão de IA configurada. Peça ao administrador para cadastrar a chave em Inteligência artificial.');await aiLimit();try{return {...await runProfile(route.primary,context,false,dataset,purpose),usedFallback:false}}catch(e){if(!(e instanceof ProviderError)||!e.retryable||!route.allowFallback||!route.fallback)throw e;return {...await runProfile(route.fallback,context,false,dataset,purpose),usedFallback:true}}}
/** Operations chat: one hourly-quota unit per question; primary connection, fallback on retryable errors; logged in ai_runs. */
export async function runChat(messages:ChatMessage[],tools:ChatTool[],run:(name:string,args:Record<string,unknown>)=>{result:unknown;summary:string},transport:typeof fetch=fetch){
 const route=await routing();if(!route.primary)throw new ProviderError(false,'Nenhuma conexão de IA configurada.');await aiLimit();const db=database(),master=aiEnv().AI_VAULT_KEY;if(!master)throw new ProviderError(false,'Cofre de chaves indisponível.');
 const once=async(id:string)=>{const p=await db.prepare('SELECT * FROM ai_profiles WHERE id=? AND enabled=1').bind(id).first<any>();if(!p)throw new ProviderError(false,'Conexão indisponível. Selecione uma conexão ativa.');const begin=Date.now(),runId=crypto.randomUUID(),log=(status:string,out:string,i:number|null,o:number|null)=>db.prepare('INSERT INTO ai_runs(id,profile_id,provider,model,dataset,purpose,created_at,status,duration_ms,input_tokens,output_tokens,output) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)').bind(runId,p.id,p.provider,p.model,'real','chat',new Date().toISOString(),status,Date.now()-begin,i,o,out.slice(0,12000)).run();
  let key:string;try{key=await openKey(p.cipher,master,p.id+':'+p.provider)}catch{await log('failed','Credencial ilegível.',null,null);throw new ProviderError(false,'Não foi possível abrir a credencial. Cadastre a chave novamente.')}
  try{const r=await chatWithTools(p as Profile,key,messages,tools,run,transport);await log('succeeded',r.text,r.input,r.output);return {...r,provider:p.provider as string,model:p.model as string}}catch(e){await log('failed',e instanceof Error?e.message:'erro',null,null);throw e}};
 try{return {...await once(route.primary),usedFallback:false}}catch(e){if(!(e instanceof ProviderError)||!e.retryable||!route.allowFallback||!route.fallback)throw e;return {...await once(route.fallback),usedFallback:true}}
}
