import {database} from './db';
import {requireAdmin as requireAdminUser} from './auth';
import {invokeProvider,openKey,ProviderError,type Profile,type Purpose} from './ai-core';
export function aiEnv(){return {AI_VAULT_KEY:process.env.AI_VAULT_KEY,APP_ADMIN_EMAIL:process.env.APP_ADMIN_EMAIL}}
export async function requireAdmin(req:Request){try{return await requireAdminUser(req)}catch{throw new Error('A configuração de IA está disponível apenas para o administrador.')}}
export async function aiLimit(){const hour=new Date().toISOString().slice(0,13);const row=await database().prepare('INSERT INTO ai_quota(id,count) VALUES(?,1) ON CONFLICT(id) DO UPDATE SET count=ai_quota.count+1 RETURNING count').bind(hour).first<{count:number}>();const limit=aiHourlyLimit();if(!row||row.count>limit)throw new Error(`Limite de ${limit} solicitações de IA por hora atingido. Tente na próxima hora.`);}
/** Site-wide cap per hour; AI_HOURLY_LIMIT overrides the default. */
export function aiHourlyLimit(){const n=Number(process.env.AI_HOURLY_LIMIT);return Number.isInteger(n)&&n>0&&n<=1000?n:30}
export async function runProfile(id:string,context:string,test:boolean,dataset:string,purpose:Purpose='analysis'){const db=database();const p=await db.prepare('SELECT * FROM ai_profiles WHERE id=? AND enabled=1').bind(id).first<any>();if(!p)throw new Error('Conexão indisponível. Selecione uma conexão ativa.');const master=aiEnv().AI_VAULT_KEY;if(!master)throw new Error('Cofre de chaves indisponível.');const begin=Date.now(),runId=crypto.randomUUID();let result;try{const key=await openKey(p.cipher,master,p.id+':'+p.provider);result=await invokeProvider(p as Profile,key,context,test,fetch,purpose)}catch(e){const message=e instanceof ProviderError?e.message:'Não foi possível abrir a credencial. Cadastre a chave novamente.';await db.prepare('INSERT INTO ai_runs(id,profile_id,provider,model,dataset,purpose,created_at,status,duration_ms,input_tokens,output_tokens,output) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)').bind(runId,p.id,p.provider,p.model,dataset,test?'test':purpose,new Date().toISOString(),'failed',Date.now()-begin,null,null,message).run();if(e instanceof ProviderError)throw e;throw new Error(message)}
 await db.prepare('INSERT INTO ai_runs(id,profile_id,provider,model,dataset,purpose,created_at,status,duration_ms,input_tokens,output_tokens,output) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)').bind(runId,p.id,p.provider,p.model,dataset,test?'test':purpose,new Date().toISOString(),'succeeded',Date.now()-begin,result.input,result.output,result.text).run();return {id:runId,provider:p.provider,model:p.model,profile:p.name,...result};}
