/** Presentation layer for the category → model → grade explorer. Source values and identities stay unchanged. */
import type {Total} from './totals';
import type {Store} from './model';
export const NOT_INFORMED='Não informado',NO_CATEGORY='Categoria não informada',CATEGORY_CONFLICT='Conflito de categoria';
export type CategoryStatus='source'|'matched'|'missing'|'conflict';
export type CatalogRow={id:string;reference:string;model:string;category:string;categoryStatus:CategoryStatus;color:string;size:string;sizeCode:string;rawColor:string;rawSize:string;qty:number;amount?:number;store?:string;storeName?:string;date?:string;period?:string;origin?:string};
export type CatalogModel={key:string;reference:string;model:string;category:string;categoryStatus:CategoryStatus;qty:number;amount:number;variants:number;colors:number;stores:number;rows:CatalogRow[]};
const clean=(v:unknown)=>String(v??'').trim().replace(/\s+/g,' ');
export const searchKey=(s:string)=>s.normalize('NFD').replace(/[̀-ͯ]/g,'').toLocaleLowerCase('pt-BR');
/** `01 - 32` (vendas) and `32` (estoque) share the label; the grade code only orders columns and is never a universal size. */
export function canonSize(raw:unknown){const s=clean(raw),m=s.match(/^(\d+)\s*-\s*(.+)$/);return m?{code:m[1].padStart(2,'0'),label:m[2].trim().toUpperCase()}:{code:'',label:s.toUpperCase()}}
/** `3    - CHUMBO` and `3   -CHUMBO` → `3 - CHUMBO`. Code and name are both kept. */
export function canonColor(raw:unknown){return clean(raw).replace(/^([^\s-]+)\s*-\s*/,'$1 - ').toUpperCase()}
const letters=['XPP','PP','P','M','G','GG','XG','2XG','3XG','4XG','5XG'];
export function sizeOrder(a:string,b:string){const rank=(v:string)=>v===NOT_INFORMED?[4,0]:v==='UNI'?[3,0]:letters.includes(v)?[0,letters.indexOf(v)]:/^\d+([.,]\d+)?$/.test(v)?[1,Number(v.replace(',','.'))]:[2,0];const x=rank(a),y=rank(b);return x[0]-y[0]||x[1]-y[1]||a.localeCompare(b,'pt-BR',{numeric:true})}
export const colorOrder=(a:string,b:string)=>a===NOT_INFORMED?1:b===NOT_INFORMED?-1:a.localeCompare(b,'pt-BR',{numeric:true});
/** Category per reference from totalizations. Only an unambiguous match is reused; prefixes and names are never used to infer. */
export function categoryIndex(totals:Total[]){const map=new Map<string,Set<string>>();for(const t of totals){const ref=clean(t.reference),cat=clean(t.category);if(!ref||!cat)continue;const s=map.get(ref)||new Set<string>();s.add(cat);map.set(ref,s)}return map}
export function resolveCategory(reference:string,index:Map<string,Set<string>>):{category:string;categoryStatus:CategoryStatus}{const s=index.get(clean(reference));if(!s||!s.size)return {category:NO_CATEGORY,categoryStatus:'missing'};if(s.size>1)return {category:CATEGORY_CONFLICT,categoryStatus:'conflict'};return {category:[...s][0],categoryStatus:'matched'}}
function variant(color:unknown,size:unknown){const c=canonColor(color),z=canonSize(size);return {color:c||NOT_INFORMED,size:z.label||NOT_INFORMED,sizeCode:z.code,rawColor:String(color??''),rawSize:String(size??'')}}
export function totalsToCatalog(rows:Total[],stores:Store[]):CatalogRow[]{return rows.map(r=>{const cat=clean(r.category);return {id:r.id,reference:clean(r.reference),model:clean(r.description),category:cat||NO_CATEGORY,categoryStatus:cat?'source':'missing',...variant(r.color,r.size),qty:r.qty,amount:r.amount,store:r.store,storeName:stores.find(s=>s.id===r.store)?.name||r.store,period:`${r.start}|${r.end}`,origin:r.sourceFile||''}})}
export function stockToCatalog(rows:{id:string;sku:string;reference?:string;model?:string;color?:string;size?:string;physical:number;store:string;storeName?:string;date:string;category?:string}[],index:Map<string,Set<string>>):CatalogRow[]{return rows.map(r=>{const reference=clean(r.reference||r.sku);const cat=r.reference?resolveCategory(reference,index):r.category&&r.category!=='Sem cadastro'?{category:r.category,categoryStatus:'source' as const}:{category:NO_CATEGORY,categoryStatus:'missing' as const};return {id:r.id,reference,model:clean(r.model||r.sku),...cat,...variant(r.color,r.size),qty:r.physical,store:r.store,storeName:r.storeName||r.store,date:r.date}})}
/** Models are identified by reference; equal names with different references stay separate. */
export function groupCatalog(rows:CatalogRow[]):CatalogModel[]{
 const groups=new Map<string,{m:CatalogModel;cents:number;qty:number;cats:Set<string>}>();
 for(const r of rows){const key=r.reference||`modelo:${r.model}`;const g=groups.get(key)||{m:{key,reference:r.reference,model:r.model,category:r.category,categoryStatus:r.categoryStatus,qty:0,amount:0,variants:0,colors:0,stores:0,rows:[]},cents:0,qty:0,cats:new Set<string>()};g.m.rows.push(r);g.qty+=r.qty;g.cents+=Math.round((r.amount||0)*100);g.cats.add(r.category);groups.set(key,g)}
 return [...groups.values()].map(({m,cents,qty,cats})=>({...m,category:cats.size>1?CATEGORY_CONFLICT:m.category,categoryStatus:cats.size>1?'conflict':m.categoryStatus,qty:Math.round(qty*1e6)/1e6,amount:cents/100,variants:new Set(m.rows.map(r=>r.color+'|'+r.size)).size,colors:new Set(m.rows.map(r=>r.color)).size,stores:new Set(m.rows.map(r=>r.store).filter(Boolean)).size}));
}
export function catalogCategories(models:CatalogModel[]){const map=new Map<string,{name:string;models:number;qty:number;cents:number}>();for(const m of models){const c=map.get(m.category)||{name:m.category,models:0,qty:0,cents:0};c.models++;c.qty+=m.qty;c.cents+=Math.round(m.amount*100);map.set(m.category,c)}return [...map.values()].map(({cents,...c})=>({...c,qty:Math.round(c.qty*1e6)/1e6,amount:cents/100}))}
export function filterCatalog(models:CatalogModel[],category:string,model:string,query:string){const q=searchKey(query.trim());return models.filter(m=>(!category||m.category===category)&&(!model||m.key===model)&&(!q||searchKey([m.reference,m.model,m.category,...m.rows.map(r=>`${r.color} ${r.size} ${r.storeName||''}`)].join(' ')).includes(q)))}
/** Color rows × size columns. `undefined` = combination absent from the source (different from zero). */
export function gradeMatrix(rows:CatalogRow[]){const colors=[...new Set(rows.map(r=>r.color))].sort(colorOrder),codes=new Map<string,string>();for(const r of rows)if(r.sizeCode&&(!codes.has(r.size)||r.sizeCode<codes.get(r.size)!))codes.set(r.size,r.sizeCode);const sizes=[...new Set(rows.map(r=>r.size))].sort(sizeOrder),cells=new Map<string,{qty:number;amount:number;count:number}>();for(const r of rows){const key=JSON.stringify([r.color,r.size]),c=cells.get(key)||{qty:0,amount:0,count:0};c.qty=Math.round((c.qty+r.qty)*1e6)/1e6;c.amount=Math.round(c.amount*100+(r.amount||0)*100)/100;c.count++;cells.set(key,c)}return {colors,sizes,cells,codes}}
export const cellKey=(color:string,size:string)=>JSON.stringify([color,size]);
