/**
 * Read-only data tools for the chat. The model asks for a query (sales, stock, a model, findings, purchases) and gets
 * computed numbers back; it never sees raw files. The input is already restricted to the user's units. Names from the
 * spreadsheets are clipped and returned as data. Every result states the period, units and stock date it used.
 */
import {summarizeTotals,type Total} from './totals';
import type {Goal,Stock,Store} from './model';
import type {OpsConfig,Purchase} from './operations';
import {latestStock,priorityLabels,kindLabels,type FindingKind} from './findings';
import {canonicalize,sizeKey,type IdentityTables} from './identity';
import {searchKey,categoryIndex,resolveCategory,sizeOrder,NOT_INFORMED} from './catalog';
import {colorLabel} from './color-swatch';
import {share,avgPrice} from './metrics';
import {periodsOf,readiness,br} from './readiness';
import {computeInsights,type SavedAction,type InsightConfig} from './insights';
import {purchasePlan} from './purchasing';
export type ToolDef={name:string;description:string;parameters:Record<string,unknown>};
export type DataInput={totals:Total[];stock:Stock[];stores:Store[];goals?:Goal[];purchases?:Purchase[];saved?:SavedAction[];ops?:Partial<OpsConfig>;config?:Partial<InsightConfig>;tables?:IdentityTables;today:string;sales?:number};
const str=(d:string)=>({type:'string',description:d}),groups=['unidade','categoria','modelo','cor','tamanho'];
const filters={unidade:str('Unidade (nome ou código, ex.: JK, BC, Ecomm). Vazio = todas.'),categoria:str('Categoria (ex.: CALÇAS).'),modelo:str('Nome do modelo ou referência.'),cor:str('Cor (ex.: preto).'),tamanho:str('Tamanho (ex.: M, 38).'),periodo:str('Mês (AAAA-MM ou nome do mês). Vazio = período mais recente.')};
export const TOOLS:ToolDef[]=[
 {name:'resumo_periodo',description:'Totais de vendas do período (valor, peças, preço médio), por unidade e por categoria; saldo de estoque por unidade; comparação com período anterior quando existir; limitações dos dados. Use primeiro para perguntas gerais.',parameters:{type:'object',properties:{unidade:filters.unidade,periodo:filters.periodo}}},
 {name:'consultar_vendas',description:'Vendas totalizadas agrupadas por unidade, categoria, modelo, cor ou tamanho, com filtros. Devolve valor, peças, preço médio e participação no recorte.',parameters:{type:'object',properties:{agrupar:{type:'string',enum:groups,description:'Como agrupar.'},...filters,ordenar:{type:'string',enum:['valor','pecas'],description:'Ordenação (padrão valor).'},limite:{type:'integer',description:'Máximo de linhas (1 a 30, padrão 10).'}},required:['agrupar']}},
 {name:'consultar_estoque',description:'Saldo de estoque da última posição de cada unidade, agrupado por unidade, categoria, modelo, cor ou tamanho, com filtros. Saldo negativo conta como zero.',parameters:{type:'object',properties:{agrupar:{type:'string',enum:groups,description:'Como agrupar.'},unidade:filters.unidade,categoria:filters.categoria,modelo:filters.modelo,cor:filters.cor,tamanho:filters.tamanho,limite:{type:'integer',description:'Máximo de linhas (1 a 30, padrão 10).'}},required:['agrupar']}},
 {name:'detalhe_modelo',description:'Detalhe de um modelo por nome ou referência: vendas e saldo por unidade, por cor e tamanho, sugestão de compra e achados ligados. Modelos com o mesmo nome e referências diferentes vêm separados.',parameters:{type:'object',properties:{busca:str('Nome do modelo ou referência.'),periodo:filters.periodo},required:['busca']}},
 {name:'achados',description:'Achados calculados (faltas, transferências, estoque parado, grade, desempenho, categorias, rankings, qualidade dos dados), com fato, hipóteses, ação sugerida e limitações.',parameters:{type:'object',properties:{tipo:{type:'string',enum:['ruptura','reposicao','realocar','parado','grade','desempenho','mix','ranking','ecommerce','dados'],description:'Tipo de achado.'},unidade:filters.unidade,prioridade:{type:'string',enum:['alta','media','baixa']},limite:{type:'integer',description:'1 a 15, padrão 8.'}}}},
 {name:'sugestao_compras',description:'Sugestão de compra calculada (venda por dia × prazo de entrega + cobertura + segurança − saldo da rede), por modelo, com grade e divisão por unidade.',parameters:{type:'object',properties:{categoria:filters.categoria,urgencia:{type:'string',enum:['alta','media','baixa']},modelo:filters.modelo,limite:{type:'integer',description:'1 a 20, padrão 10.'}}}},
];
const clip=(v:unknown,n=120)=>String(v??'').replace(/[\u0000-\u001f]+/g,' ').slice(0,n);
const r2=(n:number)=>Math.round(n*100)/100;
const months=['janeiro','fevereiro','marco','abril','maio','junho','julho','agosto','setembro','outubro','novembro','dezembro'];
const short=(s:Store)=>s.name.split(' · ')[0];
const lim=(v:unknown,d:number,max:number)=>{const n=Number(v);return Number.isInteger(n)&&n>=1?Math.min(n,max):d};
type Ctx={i:DataInput;totals:Total[];stock:Stock[];periods:ReturnType<typeof periodsOf>;cache:Map<string,unknown>};
/** Heavier computations run once per conversation turn. */
const once=<T,>(c:Ctx,k:string,f:()=>T):T=>{if(!c.cache.has(k))c.cache.set(k,f());return c.cache.get(k) as T};
const planOf=(c:Ctx)=>once(c,'plan',()=>purchasePlan({totals:c.i.totals,stock:c.i.stock,stores:c.i.stores,ops:c.i.ops,purchases:c.i.purchases,saved:c.i.saved,tables:c.i.tables}));
export function toolContext(i:DataInput):Ctx{const c=canonicalize(i.totals,i.stock,i.tables);return {i,totals:c.totals,stock:c.stock,periods:periodsOf(c.totals),cache:new Map()}}
/** Unit by id, short name, full name or "ecommerce/site/online". */
function findStore(stores:Store[],q:unknown):{ids:string[]|null;error?:string}{const k=searchKey(String(q??'').trim());if(!k||k==='todas'||k==='rede')return {ids:null};const hit=stores.filter(s=>[s.id,short(s),s.name].some(x=>searchKey(x)===k)||searchKey(s.name).includes(k)||(s.type==='online'&&/(e-?commerce|site|online|loja virtual)/.test(k)));return hit.length?{ids:hit.map(s=>s.id)}:{ids:[],error:`Unidade "${clip(q,40)}" não encontrada. Opções: ${stores.filter(s=>s.status==='open').map(short).join(', ')}.`}}
const stem=(w:string)=>w.replace(/(oes|aes|s)$/,'');
function findCategory(all:string[],q:unknown):{name:string|null;error?:string}{const k=searchKey(String(q??'').trim());if(!k)return {name:null};const hit=all.find(c=>searchKey(c)===k)||all.find(c=>stem(searchKey(c))===stem(k))||all.find(c=>searchKey(c).includes(k));return hit?{name:hit}:{name:'',error:`Categoria "${clip(q,40)}" não encontrada. Opções: ${all.slice(0,20).join(', ')}.`}}
function pickPeriod(c:Ctx,q:unknown){if(!c.periods.length)return null;const k=searchKey(String(q??'').trim());let p=c.periods.at(-1)!;if(k){const m=k.match(/^(\d{4})-(\d{2})$/),mi=months.findIndex(x=>k.includes(x)),found=[...c.periods].reverse().find(x=>m?x.start.slice(0,7)===`${m[1]}-${m[2]}`:mi>=0?Number(x.start.slice(5,7))===mi+1:`${x.start}|${x.end}`===k);if(found)p=found;else return {...p,note:`Período "${clip(q,30)}" não importado; usei ${br(p.start)} a ${br(p.end)}.`}}return {...p,note:''}}
const matchText=(value:string,q:unknown)=>{const k=searchKey(String(q??'').trim());return !k||searchKey(value).includes(k)};
const sizeMatch=(value:string,q:unknown)=>{const k=String(q??'').trim().toUpperCase();return !k||sizeKey(value)===k};
function stockMeta(c:Ctx){const pos=latestStock(c.stock).filter(r=>c.i.stores.some(s=>s.id===r.store&&s.status==='open'));const dates=[...new Map(pos.map(r=>[r.store,r.date]))].map(([s,d])=>`${short(c.i.stores.find(x=>x.id===s)!)} ${br(d)}`);return {pos,dates}}
function salesRows(c:Ctx,a:Record<string,unknown>){const p=pickPeriod(c,a.periodo);if(!p)return {error:'Nenhuma totalização de vendas importada.'};const st=findStore(c.i.stores,a.unidade);if(st.error)return {error:st.error};const cats=[...new Set(c.totals.map(t=>t.category))],cat=findCategory(cats,a.categoria);if(cat.error)return {error:cat.error};
 const rows=summarizeTotals(c.totals,c.i.stores,p.start,p.end,'all').rows.filter(r=>(!st.ids||st.ids.includes(r.store))&&(!cat.name||r.category===cat.name)&&(!a.modelo||matchText(`${r.description} ${r.reference}`,a.modelo))&&matchText(colorLabel(r.color),a.cor)&&sizeMatch(r.size||'',a.tamanho));
 return {p,rows,stores:st.ids,category:cat.name}}
const groupKey=(by:string,r:{store:string;category?:string;description?:string;model?:string;reference?:string;color?:string;size?:string},stores:Store[])=>by==='unidade'?short(stores.find(s=>s.id===r.store)||{name:r.store} as Store):by==='categoria'?(r.category||'Categoria não informada'):by==='modelo'?`${clip(r.description??r.model,60)} (${r.reference})`:by==='cor'?(colorLabel(r.color)||NOT_INFORMED):(sizeKey(r.size)||NOT_INFORMED);
const scopeOf=(c:Ctx,stores:string[]|null)=>(stores?c.i.stores.filter(s=>stores.includes(s.id)):c.i.stores.filter(s=>s.status==='open')).map(short).join(', ');
export type ToolResult={result:Record<string,unknown>;summary:string};
/** Runs one tool. Errors come back as data ({erro}) so the model can correct the call or tell the user. */
export function runTool(c:Ctx,name:string,args:Record<string,unknown>):ToolResult{
 try{switch(name){
 case 'resumo_periodo':{const p=pickPeriod(c,args.periodo);if(!p)return {result:{erro:'Nenhuma totalização de vendas importada.'},summary:'sem vendas'};const st=findStore(c.i.stores,args.unidade);if(st.error)return {result:{erro:st.error},summary:'unidade não encontrada'};
  const a=summarizeTotals(c.totals,c.i.stores,p.start,p.end,'all'),rows=a.rows.filter(r=>!st.ids||st.ids.includes(r.store)),amount=r2(rows.reduce((x,r)=>x+r.amount,0)),units=rows.reduce((x,r)=>x+r.qty,0);
  const rd=readiness({totals:c.totals,stock:c.stock,stores:c.i.stores,goals:c.i.goals,sales:c.i.sales,today:c.i.today,period:`${p.start}|${p.end}`});
  const cats=new Map<string,{v:number;q:number}>();for(const r of rows){const x=cats.get(r.category)||{v:0,q:0};x.v+=r.amount;x.q+=r.qty;cats.set(r.category,x)}
  let comparacao:unknown=null;if(rd.previous){const b=summarizeTotals(c.totals,c.i.stores,rd.previous.start,rd.previous.end,'all').rows.filter(r=>(!st.ids||st.ids.includes(r.store))&&rd.previous!.stores.includes(r.store)),cur=rows.filter(r=>rd.previous!.stores.includes(r.store));const pv=r2(b.reduce((x,r)=>x+r.amount,0)),cv=r2(cur.reduce((x,r)=>x+r.amount,0));comparacao={periodoAnterior:`${br(rd.previous.start)} a ${br(rd.previous.end)}`,metodo:rd.previous.label,valorAnterior:pv,valorAtualComparavel:cv,variacaoAbs:r2(cv-pv),variacaoPct:pv>0?r2((cv/pv-1)*100):null}}
  const {pos,dates}=stockMeta(c),sp=pos.filter(r=>!st.ids||st.ids.includes(r.store));
  return {result:{periodo:`${br(p.start)} a ${br(p.end)}`,aviso:p.note||undefined,unidades:scopeOf(c,st.ids),valor:amount,pecas:units,precoMedioPorPeca:avgPrice(amount,units),porUnidade:a.channels.filter(ch=>!st.ids||st.ids.includes(ch.id)).map(ch=>({unidade:short(ch),temArquivo:ch.hasData,valor:ch.hasData?ch.amount:null,pecas:ch.hasData?ch.qty:null,participacao:ch.hasData?share(ch.amount,amount):null})),
   porCategoria:[...cats].sort((x,y)=>y[1].v-x[1].v).slice(0,12).map(([k,v])=>({categoria:k,valor:r2(v.v),pecas:v.q,participacao:share(v.v,amount)})),estoque:{data:dates.join(' · ')||'sem posição',saldo:r2(sp.reduce((x,r)=>x+r.physical,0)),variacoesComSaldo:sp.filter(r=>r.physical>0).length},comparacao,limitacoes:rd.limitations},summary:`${br(p.start)}–${br(p.end)} · ${scopeOf(c,st.ids)}`}}
 case 'consultar_vendas':{const by=String(args.agrupar);if(!groups.includes(by))return {result:{erro:`agrupar deve ser: ${groups.join(', ')}`},summary:'parâmetro inválido'};const s=salesRows(c,args);if('error' in s)return {result:{erro:s.error},summary:'filtro não encontrado'};
  const g=new Map<string,{v:number;q:number}>();for(const r of s.rows){const k=groupKey(by,r,c.i.stores),x=g.get(k)||{v:0,q:0};x.v+=r.amount;x.q+=r.qty;g.set(k,x)}const total=r2(s.rows.reduce((x,r)=>x+r.amount,0)),pcs=s.rows.reduce((x,r)=>x+r.qty,0),ord=args.ordenar==='pecas'?'q':'v';
  const linhas=[...g].sort((x,y)=>y[1][ord]-x[1][ord]).slice(0,lim(args.limite,10,30)).map(([k,v])=>({[by]:k,valor:r2(v.v),pecas:v.q,precoMedio:avgPrice(v.v,v.q),participacaoValor:share(v.v,total),participacaoPecas:share(v.q,pcs)}));
  return {result:{periodo:`${br(s.p.start)} a ${br(s.p.end)}`,aviso:s.p.note||undefined,unidades:scopeOf(c,s.stores),filtros:{categoria:s.category||undefined,modelo:args.modelo?clip(args.modelo,40):undefined,cor:args.cor?clip(args.cor,30):undefined,tamanho:args.tamanho?clip(args.tamanho,10):undefined},totalDoRecorte:{valor:total,pecas:pcs,grupos:g.size},linhas,observacao:s.rows.length?'Valores da totalização da Presence, com devoluções e ajustes.':'Nenhuma venda com esses filtros no período (ausência de arquivo não é venda zero).'},summary:`vendas por ${by}${s.category?` · ${s.category}`:''}${s.stores?` · ${scopeOf(c,s.stores)}`:''}`}}
 case 'consultar_estoque':{const by=String(args.agrupar);if(!groups.includes(by))return {result:{erro:`agrupar deve ser: ${groups.join(', ')}`},summary:'parâmetro inválido'};const st=findStore(c.i.stores,args.unidade);if(st.error)return {result:{erro:st.error},summary:'unidade não encontrada'};
  const idx=categoryIndex(c.totals),cats=[...new Set(c.totals.map(t=>t.category))],cat=findCategory(cats,args.categoria);if(cat.error)return {result:{erro:cat.error},summary:'categoria não encontrada'};
  const {pos,dates}=stockMeta(c);const rows=pos.filter(r=>(!st.ids||st.ids.includes(r.store))&&(!cat.name||resolveCategory(r.reference||r.sku,idx).category===cat.name)&&(!args.modelo||matchText(`${r.model} ${r.reference}`,args.modelo))&&matchText(colorLabel(r.color),args.cor)&&sizeMatch(r.size||'',args.tamanho)).map(r=>({...r,category:resolveCategory(r.reference||r.sku,idx).category,description:r.model}));
  const g=new Map<string,{s:number;n:number;z:number}>();for(const r of rows){const k=groupKey(by,r,c.i.stores),x=g.get(k)||{s:0,n:0,z:0};x.s+=r.physical;x.n++;if(r.physical===0)x.z++;g.set(k,x)}
  return {result:{dataPosicao:dates.join(' · ')||'sem posição importada',unidades:scopeOf(c,st.ids),filtros:{categoria:cat.name||undefined},saldoTotal:r2(rows.reduce((x,r)=>x+r.physical,0)),linhas:[...g].sort((x,y)=>y[1].s-x[1].s).slice(0,lim(args.limite,10,30)).map(([k,v])=>({[by]:k,saldo:r2(v.s),variacoes:v.n,zeradas:v.z})),observacao:'Saldo Base da Presence; negativo conta como zero; sem reservas nem trânsito. Categoria do estoque vem da referência nas totalizações.'},summary:`estoque por ${by}${cat.name?` · ${cat.name}`:''}${st.ids?` · ${scopeOf(c,st.ids)}`:''}`}}
 case 'detalhe_modelo':{const q=String(args.busca??'').trim();if(!q)return {result:{erro:'Informe o nome ou a referência.'},summary:'sem busca'};const p=pickPeriod(c,args.periodo);
  const refs=new Map<string,string>();for(const t of c.totals)if(matchText(`${t.description} ${t.reference}`,q))refs.set(t.reference,t.description);for(const r of latestStock(c.stock))if(matchText(`${r.model} ${r.reference}`,q))refs.set(r.reference||r.sku,r.model||r.sku);
  if(!refs.size){const names=[...new Set(c.totals.map(t=>t.description))].filter(n=>searchKey(q).split(' ').some(w=>w.length>2&&searchKey(n).includes(w))).slice(0,8);return {result:{erro:`Nenhum modelo com "${clip(q,40)}".`,parecidos:names},summary:'modelo não encontrado'}}
  const plan=planOf(c),ins=once(c,`ins:${p?p.start:''}`,()=>computeInsights({...c.i,period:p?`${p.start}|${p.end}`:undefined}).insights);
  const pos=latestStock(c.stock),sales=p?summarizeTotals(c.totals,c.i.stores,p.start,p.end,'all').rows:[];
  const modelos=[...refs].slice(0,4).map(([ref,name])=>{const sr=sales.filter(r=>r.reference===ref),kr=pos.filter(r=>(r.reference||r.sku)===ref),cell=new Map<string,{vendeu:number;saldo:number|null}>();for(const r of sr){const k=`${colorLabel(r.color)}|${sizeKey(r.size)}`,x=cell.get(k)||{vendeu:0,saldo:null};x.vendeu+=r.qty;cell.set(k,x)}for(const r of kr){const k=`${colorLabel(r.color)}|${sizeKey(r.size)}`,x=cell.get(k)||{vendeu:0,saldo:null};x.saldo=(x.saldo||0)+r.physical;cell.set(k,x)}
   const sug=plan?.suggestions.find(s=>s.reference===ref);
   return {referencia:ref,modelo:clip(name,80),categoria:sr[0]?.category||'',vendas:{valor:r2(sr.reduce((x,r)=>x+r.amount,0)),pecas:sr.reduce((x,r)=>x+r.qty,0),porUnidade:c.i.stores.filter(s=>sr.some(r=>r.store===s.id)).map(s=>({unidade:short(s),pecas:sr.filter(r=>r.store===s.id).reduce((x,r)=>x+r.qty,0)}))},
    saldo:{total:r2(kr.reduce((x,r)=>x+r.physical,0)),porUnidade:c.i.stores.filter(s=>kr.some(r=>r.store===s.id)).map(s=>({unidade:short(s),saldo:r2(kr.filter(r=>r.store===s.id).reduce((x,r)=>x+r.physical,0))}))},
    grade:[...cell].map(([k,v])=>({cor:k.split('|')[0],tamanho:k.split('|')[1],...v})).sort((x,y)=>x.cor.localeCompare(y.cor)||sizeOrder(x.tamanho,y.tamanho)).slice(0,60),
    sugestaoCompra:sug?{pedir:sug.qty,urgencia:priorityLabels[sug.urgency],curva:sug.abc,coberturaDias:sug.coverage,divisao:sug.split.map(x=>`${x.short} ${x.qty}`).join(' · ')}:null,
    achados:ins.filter(f=>f.reference===ref).slice(0,4).map(f=>({tipo:kindLabels[f.kind],unidade:f.storeName.split(' · ')[0],titulo:clip(f.title),acao:clip(f.action||f.suggestion,160)}))}});
  return {result:{periodo:p?`${br(p.start)} a ${br(p.end)}`:'sem vendas',encontrados:refs.size,modelos,observacao:refs.size>4?`Mais ${refs.size-4} modelos com esse termo; refine a busca.`:undefined},summary:`modelo "${clip(q,30)}" · ${refs.size} encontrado(s)`}}
 case 'achados':{const st=findStore(c.i.stores,args.unidade);if(st.error)return {result:{erro:st.error},summary:'unidade não encontrada'};const {insights,readiness:rd}=once(c,'insights',()=>computeInsights(c.i));
  const list=insights.filter(f=>(!args.tipo||f.kind===args.tipo)&&(!args.prioridade||f.priority===args.prioridade)&&(!st.ids||st.ids.some(s=>f.store===s||f.from===s||f.to===s))).slice(0,lim(args.limite,8,15));
  return {result:{periodo:rd.period?`${br(rd.period.start)} a ${br(rd.period.end)}`:'—',unidades:scopeOf(c,st.ids),total:list.length,achados:list.map(f=>({prioridade:priorityLabels[f.priority],tipo:kindLabels[f.kind as FindingKind],unidade:f.storeName.split(' · ')[0],titulo:clip(f.title),fato:clip(f.fact||f.evidence[0],220),numeros:f.metrics,hipoteses:(f.hypotheses||[]).map(h=>clip(h.text,160)),acao:clip(f.action||f.suggestion,180),limitacoes:(f.limitations||[]).slice(0,2).map(l=>clip(l,160))}))},summary:`achados${args.tipo?` · ${args.tipo}`:''}${args.prioridade?` · ${args.prioridade}`:''}`}}
 case 'sugestao_compras':{const plan=planOf(c);if(!plan)return {result:{erro:'Sem totalização de vendas para calcular compras.'},summary:'sem vendas'};
  const cats=[...new Set(plan.suggestions.map(s=>s.category))],cat=findCategory(cats,args.categoria);if(cat.error)return {result:{erro:cat.error},summary:'categoria não encontrada'};
  const list=plan.suggestions.filter(s=>(!cat.name||s.category===cat.name)&&(!args.urgencia||s.urgency===args.urgencia)&&(!args.modelo||matchText(`${s.model} ${s.reference}`,args.modelo)));
  return {result:{metodo:plan.method,periodo:plan.periodLabel,resumo:{pecas:list.reduce((x,s)=>x+s.qty,0),modelos:list.length,totalRedePecas:plan.summary.pieces,totalRedeModelos:plan.summary.models,urgenciaAlta:plan.summary.alta},modelos:list.slice(0,lim(args.limite,10,20)).map(s=>({modelo:clip(s.model,80),referencia:s.reference,categoria:s.category,urgencia:priorityLabels[s.urgency],curva:s.abc,vendeu:s.sold,saldoRede:s.stock,coberturaDias:s.coverage,pedir:s.qty,grade:s.lines.filter(l=>l.qty).map(l=>`${colorLabel(l.color)} ${l.size}: ${l.qty}`).join(' · ').slice(0,300),divisao:s.split.map(x=>`${x.short} ${x.qty}`).join(' · ')})),limitacoes:plan.limitations},summary:`compras${cat.name?` · ${cat.name}`:''}${args.urgencia?` · ${args.urgencia}`:''}`}}
 default:return {result:{erro:`Ferramenta desconhecida: ${clip(name,40)}`},summary:'ferramenta desconhecida'}}
 }catch(e){return {result:{erro:'Falha ao consultar os dados.'},summary:`erro: ${e instanceof Error?e.message.slice(0,80):''}`}}
}
