import { env } from 'cloudflare:workers';
export function database(){const db=(env as unknown as {DB:D1Database}).DB;if(!db)throw new Error('Banco indisponível. Tente novamente.');return db}
export function bucket(){const b=(env as unknown as {BUCKET:R2Bucket}).BUCKET;if(!b)throw new Error('Arquivos indisponíveis. Tente novamente.');return b}
export function json(data:unknown,status=200){return Response.json(data,{status,headers:{'Cache-Control':'no-store'}})}
export function checkOrigin(req:Request){const origin=req.headers.get('origin');if(origin&&origin!==new URL(req.url).origin)throw new Error('Origem não permitida.');}
export function fail(e:unknown){console.error(e);return json({error:e instanceof Error?e.message:'Não foi possível concluir. Tente novamente.'},400)}
export async function readRecords(){const rows=await database().prepare(`SELECT kind,payload FROM (SELECT r.kind,r.payload,ROW_NUMBER() OVER(PARTITION BY r.kind,r.rid ORDER BY i.created_at DESC,i.id DESC) AS rn FROM records r JOIN imports i ON i.id=r.import_id WHERE i.status='ready' AND r.kind!='totals' AND (r.kind!='stock' OR NOT EXISTS (SELECT 1 FROM stock_batches b WHERE b.store=json_extract(r.payload,'$.store') AND b.date=json_extract(r.payload,'$.date') AND b.import_id!=r.import_id))) WHERE rn=1 LIMIT 100001`).all<{kind:string;payload:string}>();if(rows.results.length>100000)throw new Error('A base excedeu o limite do piloto. Solicite ampliação.');const data:any={sales:[],products:[],stock:[],goals:[],purchases:[],controls:[],totals:[]};for(const r of rows.results)data[r.kind]?.push(JSON.parse(r.payload));data.totals=await readTotals();return data;}

export async function readTotals(){const rows=await database().prepare(`SELECT r.payload,i.name,i.created_at FROM total_batches b JOIN imports i ON i.id=b.import_id JOIN records r ON r.import_id=b.import_id AND r.kind='totals' WHERE i.status='ready' ORDER BY i.created_at DESC LIMIT 100001`).all<{payload:string;name:string;created_at:string}>();if(rows.results.length>100000)throw new Error('Totalizações excedem o limite do piloto.');return rows.results.map(r=>({...JSON.parse(r.payload),sourceFile:r.name,importedAt:r.created_at}));}

export async function cleanupResetFiles(){const db=database(),row=await db.prepare("SELECT payload FROM settings WHERE id='__reset_files'").first<{payload:string}>();if(!row)return;const keys=JSON.parse(row.payload) as string[];if(!Array.isArray(keys)||keys.some(k=>typeof k!=='string'||!/^imports\/[a-zA-Z0-9-]+\/original$/.test(k)))throw new Error('Lista de arquivos para limpeza inválida.');if(keys.length){const files=bucket();for(let i=0;i<keys.length;i+=100)await files.delete(keys.slice(i,i+100))}await db.prepare("DELETE FROM settings WHERE id='__reset_files'").run();}
