/**
 * Insights engine. Layers:
 *  A. trusted data  → identity.ts (canonical references), readiness.ts (period, stock date, coverage, comparability)
 *  B. metrics       → metrics.ts (one definition per indicator)
 *  C. diagnostics   → this file: performance, mix, rankings, stock/grade, unit differences, e-commerce, purchases
 *  D. interpretation→ ai-context.ts / analyst.ts send these structured insights to the model
 *  E. follow-up     → actions (FindingsBoard + /api/actions) keep status, owner, due date, baseline and observed evolution
 * Every insight separates fact, hypotheses, recommendation and limitations. No lost revenue, ROI or causality is estimated.
 */
import {summarizeTotals,type Total} from './totals';
import type {Goal,Stock,Store} from './model';
import type {Purchase} from './operations';
import {computeFindings,latestStock,type Finding,type Hypothesis,type Priority,type Quality} from './findings';
import {readiness,br,type Readiness} from './readiness';
import {canonicalize,colorKey,sizeKey,nearCollisions,typeOf,type IdentityTables} from './identity';
import {growth,share,ppChange,contribution,sellThrough,concentration,itemsToHalf,attainment,type MetricId} from './metrics';
export type Insight=Finding;
export type InsightConfig={minBaseQty:number;minBaseAmount:number;dropPct:number;materialShare:number;ppThreshold:number;topN:number;strHigh:number;strLow:number;minStock:number;staleDays:number;maxPerFront:number};
export const defaultInsightConfig:InsightConfig={minBaseQty:5,minBaseAmount:5000,dropPct:10,materialShare:2,ppThreshold:2,topN:20,strHigh:80,strLow:10,minStock:10,staleDays:7,maxPerFront:5};
export function validateInsightConfig(v:unknown):InsightConfig{const x={...defaultInsightConfig,...(v&&typeof v==='object'?v:{})} as Record<string,unknown>;for(const k of Object.keys(defaultInsightConfig))if(typeof x[k]!=='number'||!Number.isFinite(x[k] as number)||(x[k] as number)<0||(x[k] as number)>1e9)throw new Error('Parâmetros de análise inválidos.');return x as InsightConfig}
export type SavedAction={dataset:string;status:string;payload:string;updated_at?:string};
export type InsightInput={totals:Total[];stock:Stock[];stores:Store[];goals?:Goal[];sales?:number;purchases?:Purchase[];collections?:boolean;routes?:number;saved?:SavedAction[];today:string;period?:string;config?:Partial<InsightConfig>;tables?:IdentityTables};
const money=(v:number)=>Math.abs(v)>=1e6?`R$ ${(v/1e6).toLocaleString('pt-BR',{maximumFractionDigits:2})} mi`:Math.abs(v)>=1e4?`R$ ${(v/1e3).toLocaleString('pt-BR',{maximumFractionDigits:0})} mil`:v.toLocaleString('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0});
const n=(v:number)=>v.toLocaleString('pt-BR',{maximumFractionDigits:1});
const pc=(v:number|null)=>v===null?'—':`${v>0?'+':''}${n(v)}%`;
const pp=(v:number|null)=>v===null?'—':`${v>0?'+':''}${n(v)} p.p.`;
const mods=(k:number)=>`${k} ${k===1?'modelo':'modelos'}`,verb=(k:number,one:string,many:string)=>k===1?one:many;
const sgn=(v:number)=>`${v>0?'+':v<0?'−':''}${money(Math.abs(v))}`;
const r6=(v:number)=>Math.round(v*1e6)/1e6;
/** Stable short hash of what an insight says; a new fingerprint means the situation changed. */
export function fingerprint(x:unknown){const s=JSON.stringify(x);let h=5381;for(let i=0;i<s.length;i++)h=(h*33^s.charCodeAt(i))>>>0;return h.toString(36)}
type Agg={qty:number;amount:number;model:string;category:string};
function byRef(rows:Total[],keyOf:(t:Total)=>string){const m=new Map<string,Agg>();for(const t of rows){const k=keyOf(t),a=m.get(k)||{qty:0,amount:0,model:t.description,category:t.category};a.qty+=t.qty;a.amount=Math.round((a.amount+t.amount)*100)/100;m.set(k,a)}return m}
const TRANSFER_MISSING=['Reservas','Transferências em andamento','Entradas previstas','Rotas, prazos e custos'];
export function computeInsights(input:InsightInput){
 const cfg={...defaultInsightConfig,...input.config},stores=input.stores,name=(id:string)=>stores.find(s=>s.id===id)?.name||id,short=(id:string)=>name(id).split(' · ')[0];
 const {totals,stock:stockAll}=canonicalize(input.totals,input.stock,input.tables);
 const rd=readiness({totals,stock:stockAll,stores,goals:input.goals,sales:input.sales,purchases:input.purchases?.length,collections:input.collections,routes:input.routes,today:input.today,period:input.period,staleDays:cfg.staleDays,types:Object.keys(input.tables?.types||{}).length});
 const cur=rd.period,prev=rd.previous,periodKey=cur?`${cur.start}|${cur.end}`:'',periodLabel=cur?`${br(cur.start)} a ${br(cur.end)}`:'';
 const baseLimits=[...(cur?.partial?[`Período parcial (${cur.days} de ${cur.monthDays} dias).`]:[]),...(cur&&cur.end>=input.today?['O período vai até hoje ou depois: vendas podem estar incompletas.']:[])];
 const stock=latestStock(stockAll),stockDate=new Map(rd.stockDates.map(s=>[s.store,s])),out:Insight[]=[];
 const scope=(stores:string[],extra:Partial<NonNullable<Insight['scope']>>={})=>({period:periodLabel,compare:prev?`${br(prev.start)} a ${br(prev.end)} (${prev.label})`:undefined,stores,...extra});
 const quality=(reasons:string[]):Quality=>({level:reasons.length?'parcial':'suficiente',reasons});
 const staleOf=(ids:string[])=>ids.flatMap(id=>{const s=stockDate.get(id);return s?.stale?[`Estoque de ${s.name} com ${s.ageDays} dias.`]:[]});
 // Stock per unit|ref and per unit|ref|color|size. Absent key = not informed (not zero).
 const refStock=new Map<string,number>(),varStock=new Map<string,number>();for(const r of stock){const ref=r.reference||r.sku;refStock.set(`${r.store}|${ref}`,r6((refStock.get(`${r.store}|${ref}`)||0)+r.physical));const vk=`${r.store}|${ref}|${colorKey(r.color)}|${sizeKey(r.size)}`;varStock.set(vk,r6((varStock.get(vk)||0)+r.physical))}
 const stockUnits=new Set(stock.map(s=>s.store));
 const balanceOf=(store:string,ref:string)=>stockUnits.has(store)?refStock.get(`${store}|${ref}`)??null:undefined;
 // ---- Operational findings (unit differences, stock-outs, idle stock, negatives, data) enriched with the contract.
 const base=computeFindings(totals,stockAll,stores,{today:input.today,staleDays:cfg.staleDays,period:periodKey});
 for(const f of base){
  const involved=[f.store,f.from,f.to].filter((x):x is string=>!!x&&x!=='all');const lim=[...baseLimits,...staleOf(involved)];const hyp:Hypothesis[]=[];let front='dados',metricIds:MetricId[]=['saldo_fisico'];
  if(f.kind==='ruptura'||f.kind==='reposicao'||f.kind==='realocar'){front='transferencias';metricIds=['pecas','saldo_fisico'];lim.push('Quantidade é limite superior pela regra (origem preserva o que vendeu), não uma quantidade otimizada.');if(f.stockInformed===false)lim.push(`A referência não consta no estoque de ${short(f.to||f.store)}: saldo não informado.`);
   if(f.kind!=='realocar')hyp.push({text:`A falta de saldo pode ter limitado as vendas em ${short(f.to||f.store)}.`,support:`${f.metrics?.[0]?.value||''} vendidas no período e saldo ${f.metrics?.[1]?.value||'0'} na posição de ${br(stockDate.get(f.to||f.store)?.date||'')}.`,validateWith:['Data em que o saldo zerou','Procura registrada na loja']});
   else hyp.push({text:`O modelo pode ter mais procura em ${short(f.to!)} do que em ${short(f.from!)}.`,support:f.evidence[1],validateWith:['Exposição e grade na origem','Venda por tamanho no destino']});}
  if(f.kind==='parado'){front='grade';hyp.push({text:'Exposição, preço ou grade disponível podem explicar a falta de giro.',validateWith:['Exposição na loja','Tamanhos disponíveis','Chegada recente do produto']});lim.push('Sem histórico de estoque: não se sabe há quanto tempo o saldo está parado.')}
  const target=f.to||(f.kind==='parado'||f.kind==='negativo'||f.kind==='dados'?undefined:f.store);
  const follow=f.reference&&target?{label:`Saldo ${short(target)}`,store:target,reference:f.reference,value:balanceOf(target,f.reference)??null,date:stockDate.get(target)?.date||''}:undefined;
  out.push({...f,front,scope:scope(involved.length?involved:[...stockUnits],{reference:f.reference}),fact:f.reference?`${f.title} (${f.reference}) · ${short(f.to||f.store)}: ${f.evidence[0]}`:f.evidence[0],hypotheses:hyp,limitations:lim,missing:front==='transferencias'?TRANSFER_MISSING.filter(m=>!(m.startsWith('Rotas')&&input.routes)):[],quality:quality([...staleOf(involved),...(f.stockInformed===false?['Saldo não informado na unidade de destino.']:[])]),metricIds,groupKey:f.reference?`${f.to||f.store}|${f.reference}`:f.id,follow,weight:Number(f.metrics?.[0]?.value?.match(/[\d.,]+/)?.[0].replace('.','').replace(',','.'))||0});
 }
 if(!cur){return finish(out,rd,input,cfg)}
 const a=summarizeTotals(totals,stores,cur.start,cur.end,'all'),withFile=a.channels.filter(c=>c.hasData);
 const b=prev?summarizeTotals(totals,stores,prev.start,prev.end,'all'):null;
 // Daily-average method only when a partial month is compared to a full month (explicit in every text).
 const kCur=prev?.method==='media_diaria'?1/cur.days:1,kPrev=prev?.method==='media_diaria'?1/((Date.parse(prev.end)-Date.parse(prev.start))/86400000+1):1,unitSuffix=prev?.method==='media_diaria'?' por dia':'';
 const comp=new Set(prev?.stores||[]),curC=a.rows.filter(r=>comp.has(r.store)),prevC=b?b.rows.filter(r=>comp.has(r.store)):[];
 const sum=(rows:Total[])=>Math.round(rows.reduce((s,r)=>s+r.amount,0)*100)/100;
 // ---- A. Performance
 {const totCur=sum(curC)*kCur,totPrev=sum(prevC)*kPrev,g=growth(totCur,totPrev,cfg.minBaseAmount*kPrev);
  const lines=withFile.map(c=>{const sc=share(c.amount,a.amount);if(!prev||!comp.has(c.id))return {id:c.id,delta:0,text:`${c.name}: ${money(c.amount)} · ${n(c.qty)} peças · ${n(sc??0)}% do valor${prev?' (sem arquivo comparável no período anterior)':''}`};
   const pc0=sum(prevC.filter(r=>r.store===c.id))*kPrev,cc=c.amount*kCur,gg=growth(cc,pc0,cfg.minBaseAmount*kPrev);return {id:c.id,delta:gg.abs,pct:gg.pct,text:`${c.name}: ${money(pc0)} → ${money(cc)}${unitSuffix} (${pc(gg.pct)}; ${sgn(gg.abs)}; contribuição ${n(contribution(gg.abs,g.abs)??0)}% da variação) · participação ${pp(ppChange(share(cc,totCur),share(pc0,totPrev)))}`}});
  const worst=[...lines].filter(l=>l.delta<0).sort((x,y)=>x.delta-y.delta)[0];
  const outs=out.filter(f=>(f.kind==='ruptura'||f.kind==='reposicao')&&worst&&f.to===worst.id);
  const hyp:Hypothesis[]=prev&&g.abs<0?[...(worst&&outs.length?[{text:`Faltas de produto podem explicar parte da queda em ${short(worst.id)}.`,support:`${outs.length} modelos vendidos no período estão sem saldo em ${short(worst.id)} na posição de ${br(stockDate.get(worst.id)?.date||'')}.`,validateWith:['Desde quando o saldo está zerado','Histórico de estoque']}]:[]),{text:'Fluxo de clientes, campanhas ou calendário podem ter mudado entre os períodos.',validateWith:['Fluxo de loja','Calendário de campanhas e feriados']}]:[];
  out.push({id:`desempenho:rede:${periodKey}`,kind:'desempenho',front:'desempenho',priority:g.pct!==null&&g.pct<=-cfg.dropPct?'alta':prev&&g.abs<0?'media':'baixa',store:'all',storeName:'Rede',title:prev?`Vendas ${g.abs>=0?'subiram':'caíram'} ${g.pct===null?'':n(Math.abs(g.pct))+'% '}contra o período anterior`:'Vendas do período por unidade',subtitle:periodLabel,
   action:prev?(worst?`Ver os modelos e categorias que mais caíram em ${short(worst.id)}`:'Manter o acompanhamento por unidade'):'Importar a totalização do período anterior para comparar',
   metrics:[{label:'Valor',value:money(a.amount)},{label:'Peças',value:n(a.units)},...(prev?[{label:'Variação',value:pc(g.pct),tone:g.abs<0?'bad' as const:'good' as const}]:[{label:'Unidades',value:`${withFile.length}/${a.channels.length}`}])],
   fact:prev?`${money(totCur)}${unitSuffix} nas unidades comparáveis de ${periodLabel}, contra ${money(totPrev)}${unitSuffix} de ${br(prev.start)} a ${br(prev.end)}: ${sgn(g.abs)} (${pc(g.pct)}).`:`${money(a.amount)} e ${n(a.units)} peças líquidas de ${periodLabel} em ${withFile.length} unidade(s) com arquivo.`,
   evidence:lines.sort((x,y)=>x.delta-y.delta).map(l=>l.text),suggestion:prev?'Abrir a unidade com maior contribuição negativa e conferir modelos em queda e faltas de estoque antes de concluir a causa.':'Sem período anterior equivalente não há variação; importar o período anterior para explicar mudanças.',
   hypotheses:hyp,limitations:[...baseLimits,...(prev?.method==='media_diaria'?['Comparação por média diária: mês parcial contra mês completo.']:[]),...(prev?[]:['Sem período anterior equivalente importado: variações e rankings de mudança não são calculados.']),...(a.missing.length?[`Sem vendas no período: ${a.missing.map(c=>c.name).join(', ')} (ausência de arquivo não é venda zero).`]:[])],missing:prev?[]:['Totalização do período anterior equivalente'],quality:quality(prev?[]:['Sem comparação']),metricIds:['valor','pecas','participacao','variacao_abs','variacao_pct','contribuicao','variacao_pp'],scope:scope(withFile.map(c=>c.id)),groupKey:'rede|desempenho',weight:a.amount});
  // Per unit, when the change is material.
  if(prev&&b)for(const c of withFile.filter(c=>comp.has(c.id))){const cc=c.amount*kCur,p0=sum(prevC.filter(r=>r.store===c.id))*kPrev,gg=growth(cc,p0,cfg.minBaseAmount*kPrev);if(gg.pct===null||Math.abs(gg.pct)<cfg.dropPct||Math.abs(gg.abs)<cfg.minBaseAmount*kCur)continue;
   const mc=byRef(curC.filter(r=>r.store===c.id),t=>t.reference),mp=byRef(prevC.filter(r=>r.store===c.id),t=>t.reference);const refs=new Set([...mc.keys(),...mp.keys()]);
   const movers=[...refs].map(ref=>{const x=mc.get(ref),y=mp.get(ref);return {ref,model:(x||y)!.model,cur:(x?.amount||0)*kCur,prev:(y?.amount||0)*kPrev,d:(x?.amount||0)*kCur-(y?.amount||0)*kPrev}}).sort((x,y)=>gg.abs<0?x.d-y.d:y.d-x.d).slice(0,5);
   const cats=new Map<string,number>();for(const r of curC.filter(r=>r.store===c.id))cats.set(r.category,(cats.get(r.category)||0)+r.amount*kCur);for(const r of prevC.filter(r=>r.store===c.id))cats.set(r.category,(cats.get(r.category)||0)-r.amount*kPrev);
   const catMoves=[...cats].sort((x,y)=>gg.abs<0?x[1]-y[1]:y[1]-x[1]).slice(0,3);
   const noStock=movers.filter(m=>m.d<0&&(balanceOf(c.id,m.ref)??0)<=0&&stockUnits.has(c.id));
   out.push({id:`desempenho:${c.id}:${periodKey}`,kind:'desempenho',front:'desempenho',priority:gg.abs<0&&gg.pct<=-cfg.dropPct*2?'alta':gg.abs<0?'media':'baixa',store:c.id,storeName:c.name,title:`${short(c.id)}: vendas ${gg.abs<0?'caíram':'subiram'} ${n(Math.abs(gg.pct))}%`,subtitle:`${periodLabel} contra ${br(prev.start)} a ${br(prev.end)}`,
    action:gg.abs<0?`Conferir estoque e exposição dos modelos que mais caíram em ${short(c.id)}`:`Garantir estoque dos modelos em alta em ${short(c.id)}`,metrics:[{label:'Antes',value:money(p0)},{label:'Agora',value:money(cc)},{label:'Variação',value:sgn(gg.abs),tone:gg.abs<0?'bad':'good'}],
    fact:`${c.name}: ${money(p0)} → ${money(cc)}${unitSuffix} (${pc(gg.pct)}; ${sgn(gg.abs)}).`,evidence:[...movers.map(m=>`${m.model} (${m.ref}): ${money(m.prev)} → ${money(m.cur)} (${sgn(m.d)})`),...catMoves.map(([k,v])=>`Categoria ${k}: ${sgn(v)}`)],
    suggestion:gg.abs<0?'Validar se os modelos em queda estavam disponíveis e expostos antes de mudar compras ou metas.':'Checar se os modelos em alta têm saldo para as próximas semanas.',
    hypotheses:gg.abs<0?[...(noStock.length?[{text:'Parte da queda pode vir de falta de estoque nos modelos que mais caíram.',support:`${noStock.map(m=>m.model).slice(0,3).join(', ')} sem saldo na posição de ${br(stockDate.get(c.id)?.date||'')}.`,validateWith:['Desde quando o saldo está zerado']}]:[]),{text:'Mudança de fluxo, campanhas ou mix de coleção pode explicar a variação.',validateWith:['Fluxo de loja','Calendário comercial']}]:[],
    limitations:[...baseLimits,...staleOf([c.id])],missing:[],quality:quality(staleOf([c.id])),metricIds:['valor','variacao_abs','variacao_pct','contribuicao'],scope:scope([c.id]),groupKey:`${c.id}|desempenho`,weight:Math.abs(gg.abs)});}
  // Goals: realized × monthly goal, only when the period sits inside one month.
  if(cur.start.slice(0,7)===cur.end.slice(0,7))for(const c of withFile){const goal=(input.goals||[]).find(g=>g.store===c.id&&g.month===cur.start.slice(0,7))?.amount||stores.find(s=>s.id===c.id)?.target||0;const at=attainment(c.amount,goal);if(at===null)continue;const elapsed=Math.round(cur.days/cur.monthDays*1000)/10;const behind=at<elapsed-10;
   out.push({id:`meta:${c.id}:${cur.start.slice(0,7)}`,kind:'desempenho',front:'desempenho',priority:behind?'media':'baixa',store:c.id,storeName:c.name,title:`${short(c.id)}: ${n(at)}% da meta do mês`,subtitle:`${cur.days} de ${cur.monthDays} dias no período`,action:behind?'Rever com a loja as prioridades para o restante do mês':'Manter acompanhamento',metrics:[{label:'Realizado',value:money(c.amount)},{label:'Meta',value:money(goal)},{label:'Atingido',value:`${n(at)}%`,tone:behind?'bad':'good'}],
    fact:`${c.name} realizou ${money(c.amount)} de uma meta de ${money(goal)} (${n(at)}%), com ${n(elapsed)}% dos dias do mês no período.`,evidence:[`Meta mensal ${money(goal)}; período ${periodLabel}.`],suggestion:'Comparar o atingimento com a fração de dias decorridos; não é previsão de fechamento.',hypotheses:[],limitations:[...baseLimits,'Fração de dias não considera sazonalidade dentro do mês.'],missing:[],quality:quality([]),metricIds:['atingimento_meta'],scope:scope([c.id]),groupKey:`${c.id}|meta`,weight:goal});}
 }
 // ---- B. Categories, types and models
 {const catCur=new Map(a.categories.map(c=>[c.name,c.amount]));const totCur=a.amount;
  if(prev&&b){const totC=sum(curC)*kCur,totP=sum(prevC)*kPrev,cc=new Map<string,number>(),cp=new Map<string,number>();for(const r of curC)cc.set(r.category,(cc.get(r.category)||0)+r.amount*kCur);for(const r of prevC)cp.set(r.category,(cp.get(r.category)||0)+r.amount*kPrev);
   const rows=[...new Set([...cc.keys(),...cp.keys()])].map(cat=>{const x=cc.get(cat)||0,y=cp.get(cat)||0,sx=share(x,totC),sy=share(y,totP);return {cat,x,y,sx,sy,dpp:ppChange(sx,sy),g:growth(x,y,cfg.minBaseAmount*kPrev)}}).filter(r=>r.dpp!==null&&Math.abs(r.dpp)>=cfg.ppThreshold&&Math.max(r.sx??0,r.sy??0)>=cfg.materialShare).sort((p,q)=>Math.abs(q.dpp!)-Math.abs(p.dpp!)).slice(0,cfg.maxPerFront);
   for(const r of rows){const mc=byRef(curC.filter(t=>t.category===r.cat),t=>t.reference),mp=byRef(prevC.filter(t=>t.category===r.cat),t=>t.reference);const movers=[...new Set([...mc.keys(),...mp.keys()])].map(ref=>({ref,model:(mc.get(ref)||mp.get(ref))!.model,d:(mc.get(ref)?.amount||0)*kCur-(mp.get(ref)?.amount||0)*kPrev})).sort((p,q)=>r.dpp!<0?p.d-q.d:q.d-p.d).slice(0,3);
    const grewButLost=r.g.abs>0&&r.dpp!<0;const types=typesIn(curC.filter(t=>t.category===r.cat),input.tables);
    out.push({id:`mix:${r.cat}:${periodKey}`,kind:'mix',front:'mix',priority:r.dpp!<=-2*cfg.ppThreshold?'media':'baixa',store:'all',storeName:'Rede',title:`${r.cat}: ${r.dpp!<0?'perdeu':'ganhou'} ${n(Math.abs(r.dpp!))} p.p. de participação`,subtitle:grewButLost?'Cresceu em valor, mas menos que o total':periodLabel,
     action:r.dpp!<0?`Ver disponibilidade e exposição dos modelos de ${r.cat} em queda`:`Checar estoque dos modelos que puxaram ${r.cat}`,metrics:[{label:'Part. antes',value:`${n(r.sy??0)}%`},{label:'Part. agora',value:`${n(r.sx??0)}%`},{label:'Valor',value:sgn(r.g.abs),tone:r.g.abs<0?'bad':'good'}],
     fact:`${r.cat}: participação ${n(r.sy??0)}% → ${n(r.sx??0)}% (${pp(r.dpp)}); valor ${money(r.y)} → ${money(r.x)}${unitSuffix} (${sgn(r.g.abs)}${r.g.pct!==null?`, ${pc(r.g.pct)}`:''}).`,
     evidence:[...movers.map(m=>`${m.model} (${m.ref}): ${sgn(m.d)}`),...(types.length?[`Tipos: ${types.join(' · ')}`]:[])],suggestion:'Participação menor não é desempenho ruim por si só: confirmar meta, disponibilidade, lançamentos e papel da categoria antes de agir.',
     hypotheses:[{text:r.dpp!<0?`Menor disponibilidade ou menos lançamentos em ${r.cat} podem explicar a perda.`:`Lançamentos ou reposição em ${r.cat} podem explicar o ganho.`,validateWith:['Estoque da categoria no período anterior','Calendário de lançamentos']}],limitations:[...baseLimits,...(grewButLost?['A categoria cresceu em valor; a perda de participação vem do crescimento maior de outras.']:[])],missing:['Estoque do período anterior'],quality:quality([]),metricIds:['participacao','variacao_pp','variacao_abs'],scope:scope([...comp],{category:r.cat}),groupKey:`rede|mix|${r.cat}`,weight:Math.abs(r.g.abs)});}}
  // Concentration: how dependent the period is on a few models.
  const values=a.products.map(p=>p.amount),top10=concentration(values,10),half=itemsToHalf(values);
  if(top10!==null){const top=a.products.slice(0,10),risky=top.filter(p=>out.some(f=>(f.kind==='ruptura'||f.kind==='reposicao')&&f.reference===p.reference));
   out.push({id:`mix:concentracao:${periodKey}`,kind:'mix',front:'mix',priority:risky.length>=2&&half!==null&&half<=10?'media':'baixa',store:'all',storeName:'Rede',title:`${half} ${half===1?'modelo faz':'modelos fazem'} metade das vendas`,subtitle:`Top 10 = ${n(top10)}% do valor · ${a.products.length} modelos vendidos`,action:risky.length?'Proteger o estoque dos modelos principais com falta em alguma unidade':'Acompanhar o estoque dos 10 modelos principais',
    metrics:[{label:'Top 10',value:`${n(top10)}%`},{label:'Metade com',value:`${half} modelos`},{label:'Com falta',value:n(risky.length),tone:risky.length?'bad':undefined}],fact:`Os 10 modelos com maior valor somam ${n(top10)}% das vendas de ${periodLabel}; ${half} modelos chegam a 50%.`,
    evidence:[...top.slice(0,5).map(p=>`${p.description} (${p.reference}): ${money(p.amount)} · ${n(share(p.amount,totCur)??0)}%`),...[...catCur].slice(0,5).map(([k,v])=>`Categoria ${k}: ${n(share(v,totCur)??0)}%`)],suggestion:'Garantir grade e saldo dos modelos que concentram vendas; falta neles pesa mais no resultado.',
    hypotheses:risky.length?[{text:'Falta de estoque nos modelos principais pode limitar o resultado.',support:`${risky.map(p=>p.description).slice(0,3).join(', ')} com falta em alguma unidade.`,validateWith:['Entradas previstas']}]:[],limitations:baseLimits,missing:[],quality:quality([]),metricIds:['concentracao','participacao'],scope:scope(withFile.map(c=>c.id)),groupKey:'rede|concentracao',weight:0});}
  // Unit profile vs network: large differences in category share (not a verdict on performance).
  if(withFile.length>1)for(const c of withFile){const rows=a.rows.filter(r=>r.store===c.id),tot=sum(rows);const diffs=[...catCur].filter(([,v])=>(share(v,totCur)??0)>=cfg.materialShare).map(([cat,v])=>{const own=sum(rows.filter(r=>r.category===cat));return {cat,net:share(v,totCur)!,own:share(own,tot)??0}}).map(x=>({...x,d:Math.round((x.own-x.net)*10)/10})).filter(x=>Math.abs(x.d)>=10).sort((x,y)=>Math.abs(y.d)-Math.abs(x.d)).slice(0,3);if(!diffs.length)continue;
   out.push({id:`mix:perfil:${c.id}:${periodKey}`,kind:'mix',front:'mix',priority:'baixa',store:c.id,storeName:c.name,title:`${short(c.id)} vende um mix diferente da rede`,subtitle:diffs.map(x=>`${x.cat} ${pp(x.d)}`).join(' · '),action:'Conferir se o estoque por categoria acompanha o perfil de venda da unidade',metrics:diffs.slice(0,3).map(x=>({label:x.cat.slice(0,18),value:`${n(x.own)}% × ${n(x.net)}%`,tone:x.d<0?'bad' as const:undefined})),
    fact:`Em ${short(c.id)}, ${diffs.map(x=>`${x.cat} tem ${n(x.own)}% do valor (rede ${n(x.net)}%)`).join('; ')}.`,evidence:diffs.map(x=>`${x.cat}: unidade ${n(x.own)}% · rede ${n(x.net)}% (${pp(x.d)})`),suggestion:'Usar a diferença para calibrar estoque e exposição por unidade; não é, sozinha, sinal de problema.',
    hypotheses:[{text:'Público, espaço de loja ou disponibilidade da categoria podem explicar a diferença.',validateWith:['Estoque da categoria na unidade','Perfil de público']}],limitations:[...baseLimits,'Participação menor não significa desempenho ruim.'],missing:[],quality:quality([]),metricIds:['participacao'],scope:scope([c.id]),groupKey:`${c.id}|perfil`,weight:0});}
 }
 // ---- C. Rankings (value and pieces kept apart; full universe, not the intersection of two top lists)
 {const cm=byRef(a.rows,t=>t.reference);const byVal=[...cm].sort((x,y)=>y[1].amount-x[1].amount),byQty=[...cm].sort((x,y)=>y[1].qty-x[1].qty);
  const priorRefs=new Set(totals.filter(t=>t.end<cur.start).map(t=>t.reference)),hasHistory=priorRefs.size>0;
  let moves:{entered:string[];left:string[];newRefs:[string,Agg][];decel:number}|null=null;
  if(prev&&b){const mc=byRef(curC,t=>t.reference),mp=byRef(prevC,t=>t.reference);const rankOf=(m:Map<string,Agg>)=>new Map([...m].sort((x,y)=>y[1].amount-x[1].amount).map(([k],i)=>[k,i+1]));const rc=rankOf(mc),rp=rankOf(mp),N=cfg.topN;
   const universe=[...new Set([...mc.keys(),...mp.keys()])].map(ref=>{const x=mc.get(ref),y=mp.get(ref);const cv=(x?.amount||0)*kCur,pv=(y?.amount||0)*kPrev;return {ref,model:(x||y)!.model,cv,pv,cq:(x?.qty||0)*kCur,pq:(y?.qty||0)*kPrev,g:growth(cv,pv,cfg.minBaseAmount*kPrev)}});
   const falls=universe.filter(u=>u.pq>=cfg.minBaseQty*kPrev&&u.g.abs<=-cfg.minBaseAmount*kCur).sort((x,y)=>x.g.abs-y.g.abs).slice(0,3);
   for(const u of falls){const where=[...comp].map(s=>{const x=sum(curC.filter(t=>t.store===s&&t.reference===u.ref))*kCur,y=sum(prevC.filter(t=>t.store===s&&t.reference===u.ref))*kPrev;return {s,d:x-y,bal:balanceOf(s,u.ref)}}).filter(w=>w.d<0).sort((x,y)=>x.d-y.d);const noStock=where.filter(w=>w.bal!==undefined&&(w.bal===null||w.bal<=0));
    out.push({id:`ranking:queda:${u.ref}:${periodKey}`,kind:'ranking',front:'rankings',priority:u.g.pct!==null&&u.g.pct<=-30?'media':'baixa',store:'all',storeName:'Rede',title:`${u.model}: queda de ${u.g.pct===null?sgn(u.g.abs):n(Math.abs(u.g.pct))+'%'}`,subtitle:`${u.ref} · ${n(u.pq)} → ${n(u.cq)} peças${unitSuffix}`,action:noStock.length?`Avaliar reposição ou transferência para ${noStock.map(w=>short(w.s)).join(', ')}`:'Rever exposição e preço antes de nova compra',
     metrics:[{label:'Antes',value:money(u.pv)},{label:'Agora',value:money(u.cv)},{label:'Variação',value:sgn(u.g.abs),tone:'bad'}],fact:`${u.model} (${u.ref}) passou de ${money(u.pv)} para ${money(u.cv)}${unitSuffix} (${sgn(u.g.abs)}${u.g.pct!==null?`, ${pc(u.g.pct)}`:''}).`,
     evidence:where.map(w=>`${short(w.s)}: ${sgn(w.d)}; saldo atual ${w.bal===undefined?'sem arquivo de estoque':w.bal===null?'não consta':n(w.bal)}`),suggestion:noStock.length?'Confirmar se a queda coincide com falta de estoque antes de concluir perda de procura.':'Com saldo disponível, a queda pode ser de procura ou exposição: validar na loja.',
     hypotheses:noStock.length?[{text:'A falta de estoque pode explicar parte da queda.',support:`Sem saldo em ${noStock.map(w=>short(w.s)).join(', ')} na posição atual.`,validateWith:['Desde quando o saldo está zerado']}]:[{text:'Menor procura, exposição ou preço podem explicar a queda.',validateWith:['Exposição na loja','Dados de navegação do e-commerce']}],limitations:[...baseLimits,'Estoque atual não mostra se havia falta durante o período.'],missing:['Histórico de estoque'],quality:quality([]),metricIds:['valor','pecas','variacao_abs','variacao_pct'],scope:scope([...comp],{reference:u.ref}),groupKey:`rede|${u.ref}`,weight:Math.abs(u.g.abs)});}
   const entered=[...rc].filter(([k,r])=>r<=N&&(rp.get(k)??Infinity)>N).map(([k])=>mc.get(k)!.model),left=[...rp].filter(([k,r])=>r<=N&&(rc.get(k)??Infinity)>N).map(([k])=>mp.get(k)!.model);
   moves={entered,left,newRefs:hasHistory?[...cm].filter(([k])=>!priorRefs.has(k)).sort((x,y)=>y[1].amount-x[1].amount):[],decel:universe.filter(u=>u.g.pct!==null&&u.g.pct<=-30).length};}
  const top=(list:[string,Agg][],f:(x:Agg)=>string)=>list.slice(0,5).map(([k,v],i)=>`${i+1}. ${v.model} (${k}): ${f(v)}`);
  out.push({id:`ranking:top:${periodKey}`,kind:'ranking',front:'rankings',priority:'baixa',store:'all',storeName:'Rede',title:'Mais vendidos do período',subtitle:`Em valor: ${byVal[0]?.[1].model||'—'} · em peças: ${byQty[0]?.[1].model||'—'}`,action:moves?'Ver entradas e saídas do ranking':'Importar o período anterior para ver altas e quedas',
   metrics:[{label:'Modelos',value:n(cm.size)},...(moves?[{label:`Entraram top ${cfg.topN}`,value:n(moves.entered.length)},{label:'Novos',value:n(moves.newRefs.length)}]:[])],fact:`${byVal[0]?.[1].model||'—'} lidera em valor (${money(byVal[0]?.[1].amount||0)}) e ${byQty[0]?.[1].model||'—'} em peças (${n(byQty[0]?.[1].qty||0)}).`,
   evidence:['Em valor:',...top(byVal,v=>money(v.amount)),'Em peças:',...top(byQty,v=>`${n(v.qty)} peças`),...(moves?[`Entraram no top ${cfg.topN}: ${moves.entered.slice(0,5).join(', ')||'nenhum'}.`,`Saíram do top ${cfg.topN}: ${moves.left.slice(0,5).join(', ')||'nenhum'}.`,`${mods(moves.newRefs.length)} ${verb(moves.newRefs.length,'novo','novos')} (sem venda em períodos anteriores importados)${moves.newRefs.length?`: ${moves.newRefs.slice(0,3).map(([,v])=>v.model).join(', ')}`:''}.`,`${mods(moves.decel)} em desaceleração (queda ≥ 30% com base mínima).`]:[])],
   suggestion:'Ranking em valor e em peças respondem perguntas diferentes: preço médio alto sobe no valor, peças baratas sobem em quantidade.',hypotheses:[],limitations:[...baseLimits,...(moves?[]:['Sem período anterior equivalente importado: variações e rankings de mudança não são calculados.']),...(hasHistory?[]:['Sem histórico anterior: não dá para separar novos de recorrentes.'])],missing:moves?[]:['Período anterior equivalente'],quality:quality(moves?[]:['Sem comparação']),metricIds:['valor','pecas'],scope:scope(withFile.map(c=>c.id)),groupKey:'rede|ranking',weight:0});
 }
 // ---- D. Stock and grade health, per unit with both sales and stock
 {const soldVar=new Map<string,number>(),netSize=new Map<string,Map<string,number>>();for(const t of a.rows){const vk=`${t.store}|${t.reference}|${colorKey(t.color)}|${sizeKey(t.size)}`;soldVar.set(vk,(soldVar.get(vk)||0)+t.qty);if(t.size){const m=netSize.get(t.reference)||new Map();m.set(sizeKey(t.size),(m.get(sizeKey(t.size))||0)+t.qty);netSize.set(t.reference,m)}}
  const sold=byRef(a.rows,t=>`${t.store}|${t.reference}`);
  for(const s of withFile.filter(c=>stockUnits.has(c.id))){const lim=[...baseLimits,...staleOf([s.id])],date=br(stockDate.get(s.id)?.date||'');
   const refs=[...sold].filter(([k])=>k.startsWith(s.id+'|')).map(([k,v])=>({ref:k.slice(s.id.length+1),...v,bal:refStock.get(k)??null}));
   const high=refs.filter(r=>r.qty>=cfg.minBaseQty&&r.bal!==null&&r.bal>0).map(r=>({...r,str:sellThrough(r.qty,r.bal)!})).filter(r=>r.str>=cfg.strHigh).sort((x,y)=>y.qty-x.qty).slice(0,cfg.maxPerFront);
   if(high.length)out.push({id:`grade:giro-alto:${s.id}:${periodKey}`,kind:'grade',front:'grade',priority:'media',store:s.id,storeName:s.name,title:`${mods(high.length)} com pouco saldo para o que vendem em ${short(s.id)}`,subtitle:`STR ≥ ${cfg.strHigh}% · posição ${date}`,action:'Conferir entradas previstas e reposição desses modelos',
    metrics:[{label:'Modelos',value:n(high.length)},{label:'Vendeu',value:`${n(high.reduce((x,r)=>x+r.qty,0))} pç`},{label:'Saldo',value:n(high.reduce((x,r)=>x+(r.bal||0),0)),tone:'bad'}],fact:`${mods(high.length)} ${verb(high.length,'vendeu','venderam')} ao menos ${cfg.strHigh}% do que havia (vendido + saldo final) em ${s.name}.`,
    evidence:high.map(r=>`${r.model} (${r.ref}): vendeu ${n(r.qty)}, saldo ${n(r.bal!)}, STR ${n(r.str)}%`),suggestion:'Priorizar reposição ou transferência dos modelos com maior venda; confirmar grade antes de pedir.',hypotheses:[{text:'Pode faltar produto antes da próxima entrada.',support:'Saldo baixo frente ao vendido no período.',validateWith:['Entradas previstas','Venda diária']}],limitations:[...lim,'STR ignora recebimentos e transferências do período.'],missing:['Entradas previstas','Vendas diárias'],quality:quality(staleOf([s.id])),metricIds:['str','pecas','saldo_fisico'],scope:scope([s.id]),groupKey:`${s.id}|giro-alto`,weight:high.reduce((x,r)=>x+r.amount,0)});
   const low=refs.filter(r=>r.qty>0&&r.bal!==null&&r.bal>=cfg.minStock).map(r=>({...r,str:sellThrough(r.qty,r.bal)!})).filter(r=>r.str<=cfg.strLow).sort((x,y)=>(y.bal||0)-(x.bal||0)).slice(0,cfg.maxPerFront);
   const idleVar=stock.filter(r=>r.store===s.id&&r.physical>0&&!soldVar.has(`${s.id}|${r.reference||r.sku}|${colorKey(r.color)}|${sizeKey(r.size)}`));
   if(low.length)out.push({id:`grade:giro-baixo:${s.id}:${periodKey}`,kind:'grade',front:'grade',priority:'baixa',store:s.id,storeName:s.name,title:`${mods(low.length)} com estoque alto e pouca saída em ${short(s.id)}`,subtitle:`STR ≤ ${cfg.strLow}% com saldo ≥ ${cfg.minStock}`,action:'Rever exposição; avaliar transferência para unidade que vende o modelo',
    metrics:[{label:'Modelos',value:n(low.length)},{label:'Saldo',value:n(low.reduce((x,r)=>x+(r.bal||0),0))},{label:'Variações sem venda',value:n(idleVar.length)}],fact:`${mods(low.length)} ${verb(low.length,'vendeu','venderam')} no período mas ${verb(low.length,'tem','têm')} saldo alto em ${s.name} (STR até ${cfg.strLow}%).`,
    evidence:[...low.map(r=>`${r.model} (${r.ref}): vendeu ${n(r.qty)}, saldo ${n(r.bal!)}, STR ${n(r.str)}%`),`${idleVar.length} variações com saldo e sem venda no período (saldo ${n(r6(idleVar.reduce((x,r)=>x+r.physical,0)))}).`],suggestion:'Antes de novas compras destes modelos, avaliar exposição, preço e transferência.',hypotheses:[{text:'Exposição, preço ou grade disponível podem explicar a baixa saída.',validateWith:['Exposição na loja','Tamanhos disponíveis']}],limitations:[...lim,'Sem idade do estoque: produto pode ter chegado no fim do período.'],missing:['Data de entrada do estoque'],quality:quality(staleOf([s.id])),metricIds:['str','saldo_fisico'],scope:scope([s.id]),groupKey:`${s.id}|giro-baixo`,weight:0});
   // Size gaps: sizes that sell in the network without positive balance here, while the model has balance in other sizes.
   const gaps=[...new Set(stock.filter(r=>r.store===s.id).map(r=>r.reference||r.sku))].flatMap(ref=>{const total=refStock.get(`${s.id}|${ref}`)||0,sizes=netSize.get(ref);if(total<=0||!sizes)return [];const netQty=[...sizes.values()].reduce((x,v)=>x+v,0);if(netQty<cfg.minBaseQty)return [];
    const missing=[...sizes].filter(([z,q])=>q>0&&z!=='Não informado'&&!stock.some(r=>r.store===s.id&&(r.reference||r.sku)===ref&&sizeKey(r.size)===z&&r.physical>0));const miss=missing.reduce((x,[,q])=>x+q,0);if(!missing.length||miss/netQty<0.3)return [];
    const model=stock.find(r=>r.store===s.id&&(r.reference||r.sku)===ref)?.model||ref;return [{ref,model,total,sizes:missing.map(([z])=>z),pct:Math.round(miss/netQty*100)}]}).sort((x,y)=>y.pct-x.pct).slice(0,cfg.maxPerFront);
   if(gaps.length)out.push({id:`grade:tamanhos:${s.id}:${periodKey}`,kind:'grade',front:'grade',priority:'media',store:s.id,storeName:s.name,title:`${mods(gaps.length)} com tamanhos que vendem sem saldo em ${short(s.id)}`,subtitle:'Indício de grade incompleta (grade esperada não cadastrada)',action:'Conferir a grade na loja e avaliar transferência dos tamanhos',
    metrics:[{label:'Modelos',value:n(gaps.length)},{label:'Saldo em outros tam.',value:n(gaps.reduce((x,g)=>x+g.total,0))}],fact:`Em ${s.name}, ${mods(gaps.length)} ${verb(gaps.length,'tem','têm')} saldo, mas não nos tamanhos que responderam por pelo menos 30% das vendas do modelo na rede.`,
    evidence:gaps.map(g=>`${g.model} (${g.ref}): sem saldo em ${g.sizes.join(', ')} (${g.pct}% das peças do modelo na rede); saldo ${n(g.total)} em outros tamanhos`),suggestion:'Tratar como indício: confirmar a grade prevista antes de afirmar grade quebrada.',hypotheses:[{text:'A grade incompleta pode limitar a venda do modelo nesta unidade.',validateWith:['Grade esperada do modelo','Venda por tamanho na unidade']}],limitations:[...lim,'Tamanhos ausentes do arquivo são tratados como sem saldo positivo; não há grade esperada cadastrada.'],missing:['Grade esperada por modelo'],quality:quality(['Indício sem grade esperada',...staleOf([s.id])]),metricIds:['disponibilidade_grade','saldo_fisico'],scope:scope([s.id]),groupKey:`${s.id}|tamanhos`,weight:0});
   // Stock concentrated in one size that sells little in the network.
   const conc=[...new Set(stock.filter(r=>r.store===s.id).map(r=>r.reference||r.sku))].flatMap(ref=>{const total=refStock.get(`${s.id}|${ref}`)||0;const sizes=netSize.get(ref);if(total<cfg.minStock||!sizes)return [];const netQty=[...sizes.values()].reduce((x,v)=>x+v,0);if(netQty<cfg.minBaseQty)return [];const by=new Map<string,number>();for(const r of stock.filter(r=>r.store===s.id&&(r.reference||r.sku)===ref&&r.physical>0))by.set(sizeKey(r.size),(by.get(sizeKey(r.size))||0)+r.physical);const top=[...by].sort((x,y)=>y[1]-x[1])[0];if(!top)return [];const st=top[1]/total,sl=(sizes.get(top[0])||0)/netQty;return st>=0.6&&sl<=0.3?[{ref,model:stock.find(r=>r.store===s.id&&(r.reference||r.sku)===ref)?.model||ref,size:top[0],st:Math.round(st*100),sl:Math.round(sl*100)}]:[]}).slice(0,cfg.maxPerFront);
   if(conc.length)out.push({id:`grade:concentrado:${s.id}:${periodKey}`,kind:'grade',front:'grade',priority:'baixa',store:s.id,storeName:s.name,title:`${mods(conc.length)} com saldo concentrado em um tamanho em ${short(s.id)}`,subtitle:'Tamanho com muito saldo e pouca venda na rede',action:'Avaliar redistribuir o tamanho concentrado',metrics:[{label:'Modelos',value:n(conc.length)}],fact:`Em ${s.name}, ${mods(conc.length)} ${verb(conc.length,'tem','têm')} 60% ou mais do saldo em um tamanho que fez até 30% das vendas na rede.`,
    evidence:conc.map(c=>`${c.model} (${c.ref}): ${c.st}% do saldo no ${c.size}, que fez ${c.sl}% das peças na rede`),suggestion:'Avaliar transferência do tamanho concentrado para unidades onde ele vende.',hypotheses:[{text:'Compra ou distribuição desalinhada com a curva de tamanhos.',validateWith:['Curva de tamanhos da compra']}],limitations:lim,missing:['Grade de compra'],quality:quality(staleOf([s.id])),metricIds:['saldo_fisico'],scope:scope([s.id]),groupKey:`${s.id}|concentrado`,weight:0});
  }
 }
 // ---- F. E-commerce: availability of its best sellers in its own stock
 for(const o of stores.filter(s=>s.type==='online'&&rd.salesStores.includes(s.id)&&stockUnits.has(s.id))){const m=[...byRef(a.rows.filter(t=>t.store===o.id),t=>t.reference)].sort((x,y)=>y[1].amount-x[1].amount).slice(0,20);if(!m.length)continue;
  const none=m.filter(([ref])=>(balanceOf(o.id,ref)??0)<=0),last=m.filter(([ref])=>{const b=balanceOf(o.id,ref);return b!==null&&b!==undefined&&b>0&&b<=2});
  out.push({id:`ecommerce:disponibilidade:${o.id}:${periodKey}`,kind:'ecommerce',front:'ecommerce',priority:none.length>=3?'media':'baixa',store:o.id,storeName:o.name,title:`${none.length} dos ${m.length} mais vendidos do e-commerce sem saldo`,subtitle:`${last.length} com últimas peças (1–2)`,action:none.length?'Rever exposição dos itens sem saldo e avaliar reposição':'Acompanhar os itens com últimas peças',
   metrics:[{label:'Sem saldo',value:n(none.length),tone:none.length?'bad':undefined},{label:'Últimas peças',value:n(last.length)},{label:'Analisados',value:n(m.length)}],fact:`Entre os ${m.length} modelos que mais venderam no e-commerce em ${periodLabel}, ${none.length} estão sem saldo e ${last.length} têm 1 ou 2 peças no estoque do e-commerce.`,
   evidence:[...none.slice(0,5).map(([ref,v])=>`Sem saldo: ${v.model} (${ref}) · vendeu ${n(v.qty)}`),...last.slice(0,5).map(([ref,v])=>`Últimas peças: ${v.model} (${ref}) · saldo ${n(balanceOf(o.id,ref) as number)}`)],suggestion:'Conferir se esses produtos seguem expostos no site sem estoque.',hypotheses:[],limitations:[...baseLimits,'Sem dados de navegação, exposição ou conversão: não é possível afirmar efeito no site.'],missing:['Visualizações, carrinho e conversão','Produtos expostos/destacados'],quality:quality(['Sem dados de navegação']),metricIds:['saldo_fisico','pecas'],scope:scope([o.id]),groupKey:`${o.id}|ecommerce`,weight:0});}
 // ---- G. Purchases (only with imported orders; no plan/OTB is simulated)
 const po=(input.purchases||[]).filter(p=>p.status==='open'&&p.qty>p.received);if(po.length){const overdue=po.filter(p=>p.expected<input.today);out.push({id:`compras:abertos:${input.today}`,kind:'compras',front:'compras',priority:overdue.length?'media':'baixa',store:'all',storeName:'Rede',title:`${po.length} pedidos de compra em aberto`,subtitle:`${overdue.length} com entrega atrasada`,action:overdue.length?'Cobrar fornecedores dos pedidos atrasados':'Acompanhar recebimentos',metrics:[{label:'Em aberto',value:n(po.length)},{label:'Atrasados',value:n(overdue.length),tone:overdue.length?'bad':undefined},{label:'Peças a receber',value:n(po.reduce((x,p)=>x+p.qty-p.received,0))}],fact:`${po.length} pedidos com ${n(po.reduce((x,p)=>x+p.qty-p.received,0))} peças a receber; ${overdue.length} atrasados.`,evidence:overdue.slice(0,5).map(p=>`${p.supplier} · ${p.sku}: previsto ${br(p.expected)}`),suggestion:'Planejamento, pedido, recebimento e venda são etapas distintas; aqui só pedidos importados.',hypotheses:[],limitations:['Sem plano de coleção/OTB importado.'],missing:['Plano de coleção / OTB'],quality:quality([]),metricIds:[],scope:scope([...new Set(po.map(p=>p.store))]),groupKey:'rede|compras',weight:0})}
 // ---- Identity checks: near-identical references are reported, never merged.
 const pairs=nearCollisions(new Set([...totals.map(t=>t.reference),...stock.map(s=>s.reference||s.sku)]));if(pairs.length)out.push({id:`dados:referencias-parecidas:${pairs.length}`,kind:'dados',front:'dados',priority:'baixa',store:'all',storeName:'Rede',title:`${pairs.length} grupos de referências quase iguais`,subtitle:'Diferem só por espaço, ponto ou traço',action:'Confirmar se são o mesmo produto e cadastrar a correspondência',evidence:pairs.slice(0,5).map(p=>p.join(' · ')),suggestion:'Se forem o mesmo produto, cadastrar a tabela de correspondência (reference_aliases); o sistema não une referências por semelhança.',fact:`${pairs.length} grupos de referências diferem apenas por espaços ou pontuação.`,hypotheses:[],limitations:[],missing:[],quality:quality([]),metricIds:[],scope:scope([]),groupKey:'rede|identidade',weight:0});
 if(!rd.reconciliation.ok)out.push({id:`dados:conciliacao:${periodKey}`,kind:'dados',front:'dados',priority:'alta',store:'all',storeName:'Rede',title:'Totais não conferem com o detalhamento',action:'Revisar a importação antes de usar as análises',evidence:[`Consolidado ${money(rd.reconciliation.total||0)}; por unidade ${money(rd.reconciliation.byUnits||0)}; por categoria ${money(rd.reconciliation.byCategories||0)}.`],suggestion:'Reimportar os arquivos do período.',fact:'Soma por unidade, categoria ou modelo diferente do consolidado.',hypotheses:[],limitations:[],missing:[],quality:{level:'insuficiente',reasons:['Conciliação falhou']},metricIds:['valor'],scope:scope([]),groupKey:'rede|conciliacao',weight:0});
 return finish(out,rd,input,cfg);
}
function typesIn(rows:Total[],tables?:IdentityTables){if(!tables?.types||!Object.keys(tables.types).length)return [];const m=new Map<string,number>();for(const r of rows){const t=typeOf(r.reference,tables).value;m.set(t,(m.get(t)||0)+r.amount)}return [...m].sort((x,y)=>y[1]-x[1]).slice(0,3).map(([k,v])=>`${k} ${money(v)}`)}
const rank:Record<Priority,number>={alta:0,media:1,baixa:2};
/** Priority reasons, actions in progress, quality caps, de-duplication and stable fingerprints. */
function finish(list:Insight[],rd:Readiness,input:InsightInput,cfg:InsightConfig){
 const saved=new Map((input.saved||[]).filter(s=>s.dataset==='real').map(s=>{try{const p=JSON.parse(s.payload);return [p.id as string,{status:s.status,fingerprint:p.fingerprint as string|undefined}]}catch{return ['',{status:'',fingerprint:undefined}]}}));
 const seen=new Map<string,Insight>();
 for(const f of list){
  const reasons:string[]=[];if(f.priority==='alta')reasons.push(f.kind==='ruptura'||f.kind==='reposicao'?'Produto que vende sem saldo na unidade':f.kind==='dados'?'Dado que invalida outras análises':'Variação acima do limite configurado');
  if(f.weight)reasons.push(f.kind==='desempenho'||f.kind==='mix'||f.kind==='ranking'?`Materialidade: ${money(f.weight)}`:`Volume: ${n(f.weight)}`);
  if(f.quality?.level==='insuficiente'&&f.kind!=='dados'&&f.priority==='alta'){f.priority='media';reasons.push('Rebaixada: dados insuficientes')}
  const s=saved.get(f.id);if(s?.status==='approved'&&f.priority!=='baixa'){f.priority='baixa';reasons.push('Ação já aprovada e em andamento')}
  f.priorityReasons=reasons;f.impact=null;
  f.fingerprint=fingerprint([f.priority==='baixa'&&s?.status==='approved'?'':f.priority,f.metrics?.map(m=>m.value),f.qty]);
  // One insight per group and kind: the stronger one stays, the other is linked.
  const key=`${f.kind}|${f.groupKey||f.id}`,old=seen.get(key);if(old){if(rank[f.priority]<rank[old.priority]){f.related=[...(f.related||[]),old.id];seen.set(key,f)}else old.related=[...(old.related||[]),f.id]}else seen.set(key,f);
 }
 const insights=[...seen.values()];
 // Link explanations across fronts (e.g., a falling model with a stock-out card).
 for(const f of insights)if(f.reference){const rel=insights.filter(o=>o!==f&&o.reference===f.reference).map(o=>o.id);if(rel.length)f.related=[...new Set([...(f.related||[]),...rel])]}
 insights.sort((x,y)=>rank[x.priority]-rank[y.priority]||(x.kind==='dados'?1:0)-(y.kind==='dados'?1:0)||(y.weight||0)-(x.weight||0));
 void cfg;return {insights,readiness:rd};
}
export type Snapshot={id:string;fingerprint:string;title:string;priority:Priority};
export const snapshotOf=(list:Insight[]):Snapshot[]=>list.map(f=>({id:f.id,fingerprint:f.fingerprint||'',title:f.title,priority:f.priority}));
/** What changed since a saved snapshot: new, resolved (gone), changed (same id, different numbers) and unchanged. */
export function diffInsights(before:Snapshot[],now:Insight[]){const b=new Map(before.map(s=>[s.id,s])),c=new Map(now.map(f=>[f.id,f]));return {novos:now.filter(f=>!b.has(f.id)),resolvidos:before.filter(s=>!c.has(s.id)),alterados:now.filter(f=>b.has(f.id)&&b.get(f.id)!.fingerprint!==f.fingerprint),mantidos:now.filter(f=>b.get(f.id)?.fingerprint===f.fingerprint)}}
/** Current balance of a unit × reference for follow-up (null = not informed in the latest position). */
export function observe(stock:Stock[],store:string,reference:string,tables?:IdentityTables){const rows=latestStock(canonicalize([],stock,tables).stock).filter(r=>r.store===store);if(!rows.length)return {value:null,date:''};const ref=canonicalize([],[{reference} as Stock],tables).stock[0].reference;const m=rows.filter(r=>(r.reference||r.sku)===ref);return {value:m.length?r6(m.reduce((x,r)=>x+r.physical,0)):null,date:rows[0].date}}
