/**
 * Central metric definitions. Dashboards, reports, the insights engine and the AI context use these ids and functions,
 * so the same question never gets two different numbers. Every function returns null instead of an artificial value
 * when the denominator is zero, negative or below the relevance base.
 */
export type MetricId='valor'|'pecas'|'preco_medio_peca'|'ticket_medio'|'participacao'|'variacao_abs'|'variacao_pct'|'variacao_pp'|'contribuicao'|'atingimento_meta'|'str'|'cobertura'|'giro'|'margem'|'markup'|'saldo_fisico'|'disponivel'|'concentracao'|'disponibilidade_grade';
export type MetricDef={id:MetricId;name:string;definition:string;formula:string;granularity:string;requires:string[];limitations:string[];zero:string;missing:string};
const def=(id:MetricId,name:string,definition:string,formula:string,granularity:string,requires:string[],limitations:string[],zero:string,missing='Sem arquivo da unidade/período: indicador não calculado (ausência não é zero).'):MetricDef=>({id,name,definition,formula,granularity,requires,limitations,zero,missing});
export const METRICS:Record<MetricId,MetricDef>={
 valor:def('valor','Valor vendido (totalizado)','Soma do VALOR da totalização da Presence, com sinais originais.','Σ VALOR','unidade × período × referência/cor/tamanho',['Totalização por produto'],['Devoluções e ajustes entram com sinal negativo.','Não separa desconto, frete ou impostos.'],'—'),
 pecas:def('pecas','Peças líquidas','Soma de QT da totalização, com devoluções negativas.','Σ QT','unidade × período × variante',['Totalização por produto'],['Venda observada não equivale a demanda (faltas escondem procura).'],'—'),
 preco_medio_peca:def('preco_medio_peca','Preço médio por peça','Valor ÷ peças líquidas. Não é ticket médio por pedido.','valor ÷ peças','qualquer agregação',['Totalização por produto'],['Muda com mix e devoluções.'],'Peças ≤ 0 → não calculado.'),
 ticket_medio:def('ticket_medio','Ticket médio por pedido','Valor de vendas ÷ pedidos com venda.','Σ valor venda ÷ nº pedidos','unidade × período',['Vendas por pedido (transacionais)'],['Totalizações não trazem pedidos: indisponível só com totalização.'],'Sem pedidos → não calculado.'),
 participacao:def('participacao','Participação','Parte do valor (ou peças) sobre o total do mesmo escopo, recalculada a partir dos componentes.','parte ÷ total × 100','categoria, modelo ou unidade dentro do escopo',['Totalização por produto'],['Participação baixa não é desempenho ruim sem considerar meta, disponibilidade e papel da categoria.'],'Total ≤ 0 → não calculado.'),
 variacao_abs:def('variacao_abs','Variação absoluta','Diferença entre o período atual e o comparável.','atual − anterior','mesmo escopo nos dois períodos',['Dois períodos equivalentes importados'],['Só unidades com arquivo nos dois períodos.'],'—','Sem período comparável → não calculado.'),
 variacao_pct:def('variacao_pct','Variação percentual','Crescimento relativo sobre o período comparável.','(atual ÷ anterior − 1) × 100','mesmo escopo nos dois períodos',['Dois períodos equivalentes importados'],['Base abaixo do mínimo configurado não recebe percentual (evita % enganoso).'],'Anterior ≤ 0 ou abaixo da base mínima → não calculado.','Sem período comparável → não calculado.'),
 variacao_pp:def('variacao_pp','Mudança de participação (p.p.)','Diferença entre participações, em pontos percentuais.','part. atual − part. anterior','categoria, modelo ou unidade',['Dois períodos equivalentes importados'],['Categoria pode crescer em valor e perder participação.'],'Total do período ≤ 0 → não calculado.','Sem período comparável → não calculado.'),
 contribuicao:def('contribuicao','Contribuição para a variação','Quanto da variação consolidada vem de cada parte.','variação da parte ÷ variação total × 100','unidade, categoria ou modelo',['Dois períodos equivalentes importados'],['Com variação total próxima de zero o indicador perde sentido.'],'Variação total = 0 → não calculado.','Sem período comparável → não calculado.'),
 atingimento_meta:def('atingimento_meta','Realizado × meta','Valor realizado sobre a meta mensal da unidade.','valor ÷ meta × 100','unidade × mês',['Metas mensais importadas','Período dentro de um único mês'],['Em mês parcial mostra também a fração de dias decorridos; não é previsão de fechamento.'],'Meta ausente ou zero → não calculado.'),
 str:def('str','STR (sell-through, referência gerencial)','Parcela do estoque disponível no período que foi vendida.','peças vendidas ÷ (peças vendidas + estoque final) × 100','unidade × referência (ou variante)',['Totalização do período','Saldo Estoque próximo do fim do período'],['Adotado da referência gerencial; não existia definição anterior no sistema.','Recebimentos e transferências no período distorcem o indicador.','Estoque negativo ou não informado → não calculado.'],'Vendidas + estoque ≤ 0 → não calculado.'),
 cobertura:def('cobertura','Cobertura em dias','Dias que o disponível atende a venda média diária.','disponível ÷ venda média diária','unidade × SKU',['Vendas por pedido com ao menos 14 dias'],['Não é calculada a partir de totalizações mensais.'],'Sem venda diária → não calculado (nunca vira número artificial).'),
 giro:def('giro','Giro de estoque','Custo das vendas ÷ estoque médio a custo.','CMV ÷ estoque médio','unidade × período',['Custos','Estoque em várias datas'],['Diferente de STR e de cobertura.'],'Estoque médio = 0 → não calculado.','Sem custo ou histórico de estoque → indisponível.'),
 margem:def('margem','Margem bruta','(Receita − custo) ÷ receita.','(receita − custo) ÷ receita × 100','SKU, categoria, unidade',['Custo unitário cadastrado'],['Margem não é markup.'],'Receita ≤ 0 → não calculado.','Sem custo → indisponível.'),
 markup:def('markup','Markup','Preço ÷ custo.','preço ÷ custo','SKU',['Custo unitário cadastrado'],['Markup não é margem.'],'Custo = 0 → não calculado.','Sem custo → indisponível.'),
 saldo_fisico:def('saldo_fisico','Saldo físico (Saldo Base)','Saldo informado pela Presence na data da posição; negativo conta como zero (venda antes do lançamento da entrada).','Σ max(0, Saldo Base) por variante','unidade × data × variante',['Saldo Estoque'],['Negativo vira zero variante a variante, antes de somar; o valor original fica no arquivo importado.','Saldo fracionado é preservado.','Não informa reservas nem trânsito.'],'—','Variante sem linha no arquivo = saldo não informado (diferente de zero).'),
 disponivel:def('disponivel','Estoque disponível','Saldo físico menos reservas.','físico − reservado','unidade × SKU',['Estoque com reservas'],['O Saldo Estoque da Presence não traz reservas: disponível não é confirmado.'],'—'),
 concentracao:def('concentracao','Concentração de vendas','Participação dos N modelos que mais vendem.','Σ valor top N ÷ valor total × 100','unidade ou rede × período',['Totalização por produto'],['Depende do número de modelos ativos.'],'Total ≤ 0 → não calculado.'),
 disponibilidade_grade:def('disponibilidade_grade','Disponibilidade da grade (indício)','Tamanhos vendidos na rede sem saldo positivo na unidade.','tamanhos com saldo > 0 ÷ tamanhos vendidos na rede','unidade × modelo',['Totalização com cor/tamanho','Saldo Estoque'],['Sem grade esperada cadastrada é um indício, não “grade quebrada”.'],'Nenhum tamanho vendido → não calculado.'),
};
const r=(n:number,d=2)=>{const f=10**d;return Math.round(n*f)/f};
export const safeDiv=(a:number,b:number)=>b>0?a/b:null;
export const share=(part:number,total:number)=>total>0?r(part/total*100,1):null;
export const avgPrice=(amount:number,units:number)=>units>0?r(amount/units):null;
export const attainment=(real:number,goal:number)=>goal>0?r(real/goal*100,1):null;
export const ppChange=(cur:number|null,prev:number|null)=>cur===null||prev===null?null:r(cur-prev,1);
/** Percentage is withheld when the base is small; the absolute change is always shown. */
export function growth(cur:number,prev:number,minBase=0){const abs=r(cur-prev);const small=prev<minBase;return {abs,pct:prev>0&&!small?r((cur/prev-1)*100,1):null,smallBase:small}}
export const contribution=(partDelta:number,totalDelta:number)=>Math.abs(totalDelta)>0.005?r(partDelta/totalDelta*100,1):null;
export function sellThrough(sold:number,stock:number|null){if(stock===null||stock<0||sold<0)return null;const base=sold+stock;return base>0?r(sold/base*100,1):null}
export function concentration(values:number[],n:number){const total=values.reduce((a,v)=>a+v,0);if(total<=0)return null;const top=[...values].sort((a,b)=>b-a).slice(0,n).reduce((a,v)=>a+v,0);return r(top/total*100,1)}
/** How many items reach half of the total (a readable concentration measure). */
export function itemsToHalf(values:number[]){const total=values.reduce((a,v)=>a+v,0);if(total<=0)return null;let acc=0,i=0;for(const v of [...values].sort((a,b)=>b-a)){acc+=v;i++;if(acc>=total/2)break}return i}
export const metricBrief=(ids:MetricId[])=>[...new Set(ids)].map(id=>({indicador:METRICS[id].name,formula:METRICS[id].formula,limites:METRICS[id].limitations.slice(0,2)}));
