import {type Data,type Store,type Action,shift,inventory,num,money} from './model';
export type Purchase={id:string;store:string;sku:string;supplier:string;date:string;expected:string;qty:number;received:number;unitCost:number;status:'open'|'received'|'cancelled'};
export type Control={id:string;store:string;date:string;revenue:number;units:number};
export type Rule={sku:string;leadDays:number;minimum:number;multiple:number};
export type Route={from:string;to:string;days:number;fixedCost:number;unitCost:number};
export type OpsConfig={targetDays:number;safetyDays:number;donorDays:number;minimum:number;leadDays:number;routes:Route[];rules:Rule[]};
export const defaultOps:OpsConfig={targetDays:30,safetyDays:7,donorDays:30,minimum:8,leadDays:45,routes:[],rules:[]};
export type Decision=Action & {deadline:string;owner?:string;due?:string;reason:string;estimatedCost:number|null;arrival?:string;confidence:string;sourceDate:string;sourceFromDate?:string};
export function daysBetween(a:string,b:string){return Math.round((Date.parse(b)-Date.parse(a))/86400000)}
export function quality(data:Data,stores:Store[],asOf:string){
 const known=new Set(data.products.map(p=>p.sku));const active=stores.filter(s=>s.status==='open'&&(!s.opened||s.opened<=asOf));
 return active.map(store=>{const sales=data.sales.filter(s=>s.store===store.id&&s.date.slice(0,10)<=asOf),stocks=data.stock.filter(s=>s.store===store.id&&s.date<=asOf);const controls=(data.controls||[]).filter(c=>c.store===store.id&&c.date<=asOf);const lastSale=sales.map(s=>s.date.slice(0,10)).sort().at(-1)||'',lastStock=stocks.map(s=>s.date).sort().at(-1)||'';
 const checks=controls.map(c=>{const rows=sales.filter(s=>s.date.slice(0,10)===c.date&&s.status!=='cancelled');const value=rows.reduce((a,s)=>a+(s.status==='return'?-s.amount:s.amount),0),units=rows.reduce((a,s)=>a+(s.status==='return'?-s.qty:s.qty),0);const difference=Math.round((value-c.revenue)*100)/100;return {...c,value,actualUnits:units,difference,match:Math.abs(difference)<=.01&&units===c.units}}).sort((a,b)=>b.date.localeCompare(a.date));
 const missing=new Set([...sales,...stocks].filter(s=>!known.has(s.sku)).map(s=>s.sku));const mismatches=checks.filter(c=>!c.match);const complete=checks.filter(c=>c.match).map(c=>c.date);
 const gaps=Array.from({length:14},(_,i)=>shift(asOf,-i)).filter(d=>(!store.opened||d>=store.opened)&&!complete.includes(d));
 return {store:store.id,name:store.name,lastSale,lastStock,stockAge:lastStock?daysBetween(lastStock,asOf):null,unknown:missing.size,unknownSkus:[...missing],checks,mismatches,gaps,completeDays:complete,status:mismatches.length?'divergent':missing.size?'catalog':!lastStock||daysBetween(lastStock,asOf)>1?'stale':gaps.length?'partial':'ready'};
 });
}
export function anticipate(data:Data,stores:Store[],asOf:string,config:OpsConfig=defaultOps,saved:any[]=[],dataset='real'){
 const q=quality(data,stores,asOf),start=shift(asOf,-27),purchases=data.purchases||[];
 const active=new Set(stores.filter(s=>s.status==='open'&&(!s.opened||s.opened<=asOf)).map(s=>s.id));
 const latest=inventory(data,stores,asOf).filter(s=>active.has(s.store));
 
 const soldDays=new Map<string,number>();data.sales.filter(s=>s.status==='sale'&&s.date.slice(0,10)>=start&&s.date.slice(0,10)<=asOf).forEach(s=>{let k=`${s.store}:${s.sku}:${s.date.slice(0,10)}`;soldDays.set(k,(soldDays.get(k)||0)+s.qty)});
 const history=new Map<string,typeof data.stock>();data.stock.filter(s=>s.date>=start&&s.date<=asOf).forEach(s=>{let k=s.store+':'+s.sku;const a=history.get(k)||[];a.push(s);history.set(k,a)});
 const rows=latest.map(r=>{const qq=q.find(t=>t.store===r.store)!;const observations=(history.get(r.store+':'+r.sku)||[]).filter(s=>qq.completeDays.includes(s.date));const availableDays=[...new Set(observations.filter(s=>s.physical-s.reserved>0).map(s=>s.date))];
 const first=data.sales.filter(s=>s.store===r.store&&s.date.slice(0,10)<=asOf).map(s=>s.date.slice(0,10)).sort()[0];const elapsed=first?Math.max(1,Math.min(28,daysBetween(first,asOf)+1)):0;
 const units=Array.from({length:28},(_,i)=>soldDays.get(`${r.store}:${r.sku}:${shift(asOf,-i)}`)||0).reduce((a,b)=>a+b,0);
 const adjusted=availableDays.length>=7,daily=adjusted?availableDays.reduce((a,d)=>a+(soldDays.get(`${r.store}:${r.sku}:${d}`)||0),0)/availableDays.length:elapsed?units/elapsed:0;
 const rule=config.rules.find(t=>t.sku===r.sku),lead=rule?.leadDays??config.leadDays;
 const open=purchases.filter(p=>p.store===r.store&&p.sku===r.sku&&p.status==='open'&&p.date<=asOf&&p.qty>p.received);
 const overdue=open.filter(p=>p.expected<asOf),future=open.filter(p=>p.expected>=asOf).sort((a,b)=>a.expected.localeCompare(b.expected));
 const coverage=daily?r.available/daily:null,cutoff=shift(asOf,Math.max(config.targetDays,lead+config.safetyDays));
 const datedIncoming=future.filter(p=>p.expected<=cutoff).reduce((a,p)=>a+p.qty-p.received,0);
 const horizon=Math.max(config.targetDays,lead+config.safetyDays);const netNeed=Math.max(0,Math.ceil(daily*horizon-r.available-datedIncoming));const multiple=rule?.multiple||1,minimum=rule?.minimum||1;
 const qty=netNeed?Math.ceil(Math.max(netNeed,minimum)/multiple)*multiple:0;
 // Daily projection uses each dated order once. Past-due arrivals are deliberately excluded.
 let balance=r.available,rupture='';const projection=[];for(let n=1;n<=90;n++){let day=shift(asOf,n);const arrivals=future.filter(p=>p.expected===day||(n===1&&p.expected===asOf)).reduce((a,p)=>a+p.qty-p.received,0);balance+=arrivals;balance-=daily;if(!rupture&&daily>0&&balance<0)rupture=day;if([7,14,30,60,90].includes(n))projection.push({day,balance:Math.round(balance)})}
 const confirmed=elapsed>=14&&!qq.mismatches.length&&r.age<=1&&!!data.products.find(p=>p.sku===r.sku);const decisionDate=coverage===null?'':shift(asOf,Math.floor(coverage)-lead-config.safetyDays);
 return {...r,daily,coverage,elapsed,availableDays:availableDays.length,method:adjusted?'Dias com estoque e vendas conciliadas':'Média observada (não ajustada)',confidence:adjusted&&availableDays.length>=14?'Histórico com disponibilidade':confirmed?'Estimativa preliminar':'Dados insuficientes',lead,open,future,overdue,datedIncoming,qty,rupture,decisionDate,projection,eligible:confirmed,quality:qq.status,unverifiedIncoming:r.incoming};
 });
 const decisions:Decision[]=[],used=new Map<string,number>(),reservations=new Map<string,number>();
 for(const s of saved.filter(s=>s.dataset===dataset&&['approved','done'].includes(s.status))){const p=typeof s.payload==='string'?JSON.parse(s.payload):s.payload;const current=rows.find(r=>r.store===p?.from&&r.sku===p?.sku);if(p?.type==='transfer'&&p.from&&p.sku&&(s.status==='approved'||current&&current.date<=(p.sourceFromDate||p.sourceDate)))reservations.set(p.from+':'+p.sku,(reservations.get(p.from+':'+p.sku)||0)+p.qty)}
 const already=new Set(saved.filter(s=>s.dataset===dataset&&['approved','done'].includes(s.status)).map(s=>typeof s.payload==='string'?JSON.parse(s.payload).id:s.payload?.id));
 const riskRows=rows.filter(r=>r.eligible&&r.daily>0&&(r.qty>0||r.rupture&&r.rupture<=shift(asOf,r.lead))).sort((a,b)=>(a.rupture||'9999').localeCompare(b.rupture||'9999'));
 for(const r of riskRows){const id=`v2:${asOf}:${r.store}:${r.sku}`;const locked=saved.some(s=>{const p=typeof s.payload==='string'?JSON.parse(s.payload):s.payload;return s.dataset===dataset&&p?.sku===r.sku&&p?.to===r.store&&(s.status==='approved'||s.status==='done'&&p.sourceDate>=r.date)});if(locked)continue;const bridgeNeed=r.rupture&&r.future.length?Math.max(0,Math.ceil(r.daily*Math.min(config.targetDays,daysBetween(asOf,r.future[0].expected))-r.available)):0;const transferNeed=Math.max(bridgeNeed,Math.max(0,Math.ceil(r.daily*config.targetDays-r.available-r.future.filter(p=>p.expected<=shift(asOf,config.targetDays)).reduce((a,p)=>a+p.qty-p.received,0))));
 const donors=rows.filter(d=>d.sku===r.sku&&d.store!==r.store&&d.eligible).flatMap(d=>{const route=config.routes.find(t=>t.from===d.store&&t.to===r.store);if(!route)return[];const buffer=Math.max(config.minimum,Math.ceil(d.daily*config.donorDays));const extra=Math.max(0,d.available-buffer-(used.get(d.store+':'+d.sku)||0)-(reservations.get(d.store+':'+d.sku)||0));const qty=Math.min(transferNeed,extra);return qty>0?[{d,route,qty,cost:route.fixedCost+route.unitCost*qty}]:[]}).sort((a,b)=>a.route.days-b.route.days||a.cost-b.cost);
 const donor=donors[0];if(donor){const key=donor.d.store+':'+r.sku;used.set(key,(used.get(key)||0)+donor.qty);const arrival=shift(asOf,donor.route.days);decisions.push({id:id+':transfer',type:'transfer',title:`Transferir ${r.model} · ${r.size}`,sku:r.sku,from:donor.d.store,to:r.store,qty:donor.qty,priority:'high',detail:`${donor.d.storeName} → ${r.storeName}: ${donor.qty} peças. Chegada em ${donor.route.days} dias. Frete estimado ${money(donor.cost)}. ${r.rupture&&arrival>r.rupture?'A chegada ocorre após a ruptura estimada. Priorizar alternativa mais rápida.':''}`,reason:`Disponível ${r.available}; consumo estimado ${num(r.daily)} peça(s)/dia. Origem mantém ${config.donorDays} dias ou ${config.minimum} peças. Entradas com data consideradas uma única vez.`,deadline:r.rupture?shift(r.rupture,-donor.route.days):asOf,arrival,estimatedCost:donor.cost,confidence:r.confidence,sourceDate:r.date,sourceFromDate:donor.d.date})}
 const rest=Math.max(0,r.qty-(donor?.qty||0));if(rest){const rule=config.rules.find(s=>s.sku===r.sku),multiple=rule?.multiple||1;const qty=Math.ceil(Math.max(rest,rule?.minimum||1)/multiple)*multiple;decisions.push({id:id+':buy',type:'replenish',title:`Programar ${r.model} · ${r.size}`,sku:r.sku,to:r.store,qty,priority:r.decisionDate<=shift(asOf,7)?'high':'medium',detail:`${r.storeName}: ${qty} peças para abastecimento. Prazo de fornecimento ${r.lead} dias + ${config.safetyDays} dias de segurança. ${donor?'Quantidade desconta a transferência sugerida.':'Sem transferência viável com as rotas cadastradas.'}`,reason:`Disponível ${r.available}. Pedidos com chegada até ${cutoffLabel(asOf,Math.max(config.targetDays,r.lead+config.safetyDays))}: ${r.datedIncoming} peças. ${r.overdue.length} pedido(s) atrasado(s) excluídos.`,deadline:r.decisionDate||asOf,arrival:shift(asOf,r.lead),estimatedCost:r.cost==null?null:qty*r.cost,confidence:r.confidence,sourceDate:r.date})}if(r.rupture&&r.future.length&&r.future[0].expected>r.rupture&&(!donor||shift(asOf,donor.route.days)>r.rupture)){const order=r.future[0];decisions.push({id:id+':expedite',type:'replenish',title:`Antecipar pedido ${order.id}`,sku:r.sku,to:r.store,qty:order.qty-order.received,priority:'high',detail:`Negociar chegada até ${cutoffLabel(r.rupture,0)}. A entrega atual em ${cutoffLabel(order.expected,0)} ocorre após a falta estimada. Não é uma nova compra.`,reason:'O saldo projetado fica negativo antes da próxima entrada datada.',deadline:asOf,arrival:order.expected,estimatedCost:null,confidence:r.confidence,sourceDate:r.date})}}
 return {rows,decisions:decisions.filter(d=>!already.has(d.id)).sort((a,b)=>a.deadline.localeCompare(b.deadline)),quality:q,overdue:purchases.filter(p=>p.status==='open'&&p.date<=asOf&&p.qty>p.received&&p.expected<asOf)};
}
function cutoffLabel(asOf:string,n:number){const d=shift(asOf,n);return d.slice(8)+'/'+d.slice(5,7)}
export function validateOps(value:any,stores:Store[]):OpsConfig{if(!value||!Array.isArray(value.routes)||!Array.isArray(value.rules)||value.routes.length>30||value.rules.length>2000)throw new Error('Parâmetros inválidos.');for(const k of ['targetDays','safetyDays','donorDays','minimum','leadDays'])if(!Number.isInteger(value[k])||value[k]<0||value[k]>365)throw new Error('Use valores inteiros de 0 a 365.');if(value.targetDays<1||value.donorDays<1||value.leadDays<1)throw new Error('Prazos devem ser positivos.');const ids=new Set(stores.map(s=>s.id)),routes=new Set();for(const r of value.routes){const key=r.from+':'+r.to;if(!ids.has(r.from)||!ids.has(r.to)||r.from===r.to||routes.has(key)||!Number.isInteger(r.days)||r.days<0||r.days>60||![r.fixedCost,r.unitCost].every(v=>Number.isFinite(v)&&v>=0&&v<=100000))throw new Error('Rota inválida ou duplicada.');routes.add(key)}const rules=new Set();for(const r of value.rules){if(typeof r.sku!=='string'||!r.sku||rules.has(r.sku)||![r.leadDays,r.minimum,r.multiple].every(n=>Number.isInteger(n)&&n>0&&n<=3650))throw new Error('Regra de produto inválida.');rules.add(r.sku)}return value}
