import {type Store,dayBR} from './model';
export type Total={id:string;store:string;start:string;end:string;reference:string;category:string;description:string;qty:number;amount:number;average:number|null;size?:string;color?:string;sourceFile?:string;importedAt?:string};
export function totalId(store:string,start:string,end:string,reference:string,size='',color=''){return `${store}:${start}:${end}:${encodeURIComponent(reference)}`+(size||color?`:${encodeURIComponent(size)}:${encodeURIComponent(color)}`:'')}
export function validDate(s:unknown){return typeof s==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(s)&&Number.isFinite(Date.parse(s))&&new Date(s+'T12:00:00Z').toISOString().slice(0,10)===s}
export function totalScope(t:Pick<Total,'store'|'start'|'end'>){return `${t.store}:${t.start}:${t.end}`}
export function validateTotals(rows:Total[],stores:Store[]){if(!rows.length)throw new Error('Planilha sem produtos.');const scope=totalScope(rows[0]);for(const r of rows){if(!stores.some(s=>s.id===r.store)||!validDate(r.start)||!validDate(r.end)||r.start>r.end||totalScope(r)!==scope)throw new Error('Selecione uma única unidade e período válido para o arquivo.');if([r.size,r.color].some(v=>v!==undefined&&(typeof v!=='string'||v.length>160)))throw new Error('Cor ou tamanho inválido.');if(![r.reference,r.category,r.description].every(v=>typeof v==='string'&&!!v.trim()&&v.length<=160)||r.id!==totalId(r.store,r.start,r.end,r.reference,r.size,r.color)||!Number.isInteger(r.qty)||Math.abs(r.qty)>100000000||!Number.isFinite(r.amount)||Math.abs(r.amount)>1e12||r.average!==null&&(!Number.isFinite(r.average)||Math.abs(r.average)>1e12))throw new Error('Totalização inválida. Confira referência, campos e valores.')}if(new Set(rows.map(r=>r.id)).size!==rows.length)throw new Error('Combinação de referência, tamanho e cor duplicada no arquivo.');}
const sum=(rows:{amount:number}[])=>rows.reduce((a,r)=>a+Math.round(r.amount*100),0)/100;
export function summarizeTotals(totals:Total[],stores:Store[],start:string,end:string,channel='all'){
 const active=stores.filter(s=>s.status==='open'&&(!s.opened||s.opened<=end));const rows=totals.filter(r=>r.start===start&&r.end===end&&active.some(s=>s.id===r.store)&&(channel==='all'||r.store===channel));
 const modelStores=new Map<string,Set<string>>();const products=new Map<string,{reference:string;description:string;category:string;qty:number;amount:number;stores:number}>();for(const r of rows){const p=products.get(r.reference)||{reference:r.reference,description:r.description,category:r.category,qty:0,amount:0,stores:0};p.qty+=r.qty;p.amount=Math.round((p.amount+r.amount)*100)/100;const locations=modelStores.get(r.reference)||new Set<string>();locations.add(r.store);modelStores.set(r.reference,locations);p.stores=locations.size;if(p.category!==r.category)p.category='Categorias divergentes';products.set(r.reference,p)}
 const variants=new Map<string,{key:string;reference:string;description:string;category:string;size:string;color:string;qty:number;amount:number}>();
 for(const r of rows){const key=JSON.stringify([r.reference,r.size||'',r.color||'']);const v=variants.get(key)||{key,reference:r.reference,description:r.description,category:r.category,size:r.size||'',color:r.color||'',qty:0,amount:0};v.qty+=r.qty;v.amount=Math.round((v.amount+r.amount)*100)/100;variants.set(key,v)}
 const categories=new Map<string,number>();for(const r of rows)categories.set(r.category,(categories.get(r.category)||0)+Math.round(r.amount*100));
 const channels=active.filter(s=>channel==='all'||s.id===channel).map(s=>{const rr=rows.filter(r=>r.store===s.id),first=rr[0];return {...s,hasData:rr.length>0,amount:sum(rr),qty:rr.reduce((a,r)=>a+r.qty,0),references:new Set(rr.map(r=>r.reference)).size,sourceFile:first?.sourceFile||'',importedAt:first?.importedAt||''}});
 const units=rows.reduce((a,r)=>a+r.qty,0),amount=sum(rows);return {rows,amount,units,variants:[...variants.values()].sort((a,b)=>b.amount-a.amount),average:units>0?amount/units:null,products:[...products.values()].sort((a,b)=>b.amount-a.amount),categories:[...categories].map(([name,value])=>({name,amount:value/100})).sort((a,b)=>b.amount-a.amount),channels,negativeRows:rows.filter(r=>r.qty<0||r.amount<0),adjustments:rows.filter(r=>r.qty===0&&r.amount!==0),missing:channels.filter(c=>!c.hasData)};
}
export function totalsReport(totals:Total[],stores:Store[],start:string,end:string,channel='all'){
 const a=summarizeTotals(totals,stores,start,end,channel);return {kind:'totals',dataset:'real',type:'Consolidado',period:`${dayBR(start)} a ${dayBR(end)}`,channel:channel==='all'?'Todas as unidades':stores.find(s=>s.id===channel)?.name,createdAt:new Date().toISOString(),revenue:a.amount,units:a.units,ticket:null,average:a.average,insights:[`${a.channels.filter(c=>c.hasData).length} unidade(s) com totalização importada para o período informado.`,`${a.negativeRows.length} linha(s) com valores ou quantidades negativos preservados. ${a.adjustments.length} ajuste(s) de valor sem alteração de quantidade.`,a.missing.length?`Sem arquivo para este período: ${a.missing.map(c=>c.name).join(', ')}.`:'Todas as unidades selecionadas têm arquivo para o período.','Arquivo por modelo e, quando informados, tamanho e cor. Não contém pedidos, datas de vendas individuais ou estoque. O período informado não confirma fechamento completo.'],channels:a.channels.map(c=>({...c,revenue:c.hasData?c.amount:null,units:c.hasData?c.qty:null})),products:a.variants.map(p=>({...p,sku:p.reference,model:p.description,category:p.category})),actions:[]};
}
