import {database,bucket,json,fail,checkOrigin,readRecords} from '@/lib/db';
import {validateNormalized,type Kind} from '@/lib/imports';
import {defaultStores} from '@/lib/model';
import {totalScope,totalsReport} from '@/lib/totals';
import {reportSnapshot} from '@/lib/report';
export async function POST(req:Request){let id='';try{checkOrigin(req);if(Number(req.headers.get('content-length')||0)>48000000)throw new Error('Envio muito grande. Divida a planilha em arquivos menores.');let file:File,kind:Kind,rows:any[];
if(req.headers.get('content-type')?.includes('application/json')){const input=await req.json() as any;kind=input.kind;rows=input.rows;if(typeof input.fileName!=='string'||typeof input.fileBase64!=='string'||input.fileBase64.length>10666668)throw new Error('Selecione um arquivo de até 8 MB.');const bytes=Uint8Array.from(atob(input.fileBase64),c=>c.charCodeAt(0));file=new File([bytes],input.fileName);}else{const form=await req.formData();file=form.get('file') as File;kind=form.get('kind') as Kind;rows=JSON.parse(String(form.get('rows')||'[]'));}
if(!['sales','stock','products','goals','purchases','controls','totals'].includes(kind)||!file||file.size>8000000)throw new Error('Selecione um arquivo de até 8 MB.');
if(!Array.isArray(rows)||rows.length===0||rows.length>8000)throw new Error('Use entre 1 e 8.000 linhas por arquivo.');const db=database();const cfg=await db.prepare("SELECT payload FROM settings WHERE id='stores'").first<{payload:string}>();validateNormalized(rows,kind,cfg?JSON.parse(cfg.payload):defaultStores);const body=JSON.stringify(rows);const hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(kind+body)))).map(n=>n.toString(16).padStart(2,'0')).join('');const duplicate=await db.prepare(kind==='totals'?"SELECT i.id FROM imports i JOIN total_batches b ON b.import_id=i.id WHERE i.hash=? AND i.status='ready'":kind==='stock'?"SELECT i.id FROM imports i WHERE i.hash=? AND i.status='ready' AND NOT EXISTS (SELECT 1 FROM records r JOIN stock_batches b ON b.store=json_extract(r.payload,'$.store') AND b.date=json_extract(r.payload,'$.date') WHERE r.import_id=i.id AND b.import_id!=i.id)":"SELECT id FROM imports WHERE hash=? AND status='ready'").bind(hash).first();if(duplicate)return json({ok:true,duplicate:true,count:0,kind,stockDate:kind==='stock'?rows.reduce((a,r)=>r.date>a?r.date:a,''):null});id=crypto.randomUUID();const fileKey=`imports/${id}/original`;await bucket().put(fileKey,await file.arrayBuffer(),{httpMetadata:{contentType:'application/octet-stream'}});const statements=[db.prepare('INSERT INTO imports(id,name,kind,created_at,status,count,hash,file_key) VALUES(?,?,?,?,?,?,?,?)').bind(id,file.name.slice(0,180),kind,new Date().toISOString(),'processing',rows.length,hash,fileKey)];
// One statement per bounded JSON chunk, instead of one D1 query per row.
for(let i=0;i<rows.length;i+=80)statements.push(db.prepare("INSERT INTO records(kind,rid,import_id,payload) SELECT ?,COALESCE(json_extract(value,'$.id'),json_extract(value,'$.sku')),?,value FROM json_each(?)").bind(kind,id,JSON.stringify(rows.slice(i,i+80))));
statements.push(db.prepare("UPDATE imports SET status='ready' WHERE id=?").bind(id));
if(kind==='totals')statements.push(db.prepare('INSERT INTO total_batches(scope,store,start,end,import_id) VALUES(?,?,?,?,?) ON CONFLICT(scope) DO UPDATE SET import_id=excluded.import_id').bind(totalScope(rows[0]),rows[0].store,rows[0].start,rows[0].end,id));
if(kind==='stock'){const scopes=new Map(rows.map(r=>[JSON.stringify([r.store,r.date]),r]));for(const r of scopes.values())statements.push(db.prepare('INSERT INTO stock_batches(store,date,import_id) VALUES(?,?,?) ON CONFLICT(store,date) DO UPDATE SET import_id=excluded.import_id').bind(r.store,r.date,id));}
await db.batch(statements);
let reportWarning='';try{const data=await readRecords();const operation=await db.prepare("SELECT payload FROM settings WHERE id='operations'").first<{payload:string}>(),saved=await db.prepare('SELECT dataset,status,payload FROM actions').all();if(kind==='totals'){const report=totalsReport(data.totals,cfg?JSON.parse(cfg.payload):defaultStores,rows[0].start,rows[0].end);await db.prepare('INSERT INTO reports(id,dataset,title,created_at,payload) VALUES(?,?,?,?,?)').bind(id+':consolidated','real',`Consolidado · ${report.period} · Automático`,new Date().toISOString(),JSON.stringify(report)).run();}else if(data.sales.length){const finish=data.sales.reduce((a:string,s:any)=>s.date.slice(0,10)>a?s.date.slice(0,10):a,'');for(const type of ['Diário','Semanal','Mensal']){const report=reportSnapshot(data,cfg?JSON.parse(cfg.payload):defaultStores,finish,type,'real','all',operation?JSON.parse(operation.payload):undefined,saved.results);await db.prepare('INSERT INTO reports(id,dataset,title,created_at,payload) VALUES(?,?,?,?,?)').bind(id+':'+type,'real',`${type} · ${report.period} · Automático`,new Date().toISOString(),JSON.stringify(report)).run();}}}catch(e){console.error('Relatórios automáticos',e);reportWarning='Importação concluída. Gere o relatório manualmente na central.';}return json({ok:true,count:rows.length,id,kind,stockDate:kind==='stock'?rows.reduce((a,r)=>r.date>a?r.date:a,''):null,period:kind==='totals'?{start:rows[0].start,end:rows[0].end}:null,reportWarning});}catch(e){if(id)try{await database().prepare("UPDATE imports SET status='failed' WHERE id=?").bind(id).run()}catch{}return fail(e)}}
